/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package factory;

import java.sql.Connection;
import dao.*;
import jdbc.*;

public class FormsDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return FormsDao
	 */
	public static FormsDao create()
	{
		return new FormsDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return FormsDao
	 */
	public static FormsDao create(Connection conn)
	{
		return new FormsDaoImpl( conn );
	}

}
