/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dao;

import dto.*;
import exceptions.*;

public interface StaffDao
{
	/** 
	 * Inserts a new row in the staff table.
	 */
	public StaffPk insert(Staff dto) throws StaffDaoException;

	/** 
	 * Updates a single row in the staff table.
	 */
	public void update(StaffPk pk, Staff dto) throws StaffDaoException;

	/** 
	 * Deletes a single row in the staff table.
	 */
	public void delete(StaffPk pk) throws StaffDaoException;

	/** 
	 * Returns the rows from the staff table that matches the specified primary-key value.
	 */
	public Staff findByPrimaryKey(StaffPk pk) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria 'staff_id = :staffId'.
	 */
	public Staff findByPrimaryKey(int staffId) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria ''.
	 */
	public Staff[] findAll() throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria 'staff_id = :staffId'.
	 */
	public Staff[] findWhereStaffIdEquals(int staffId) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria 'full_name = :fullName'.
	 */
	public Staff[] findWhereFullNameEquals(String fullName) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria 'login_name = :loginName'.
	 */
	public Staff[] findWhereLoginNameEquals(String loginName) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the criteria 'password = :password'.
	 */
	public Staff[] findWherePasswordEquals(String password) throws StaffDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the staff table that match the specified arbitrary SQL statement
	 */
	public Staff[] findByDynamicSelect(String sql, Object[] sqlParams) throws StaffDaoException;

	/** 
	 * Returns all rows from the staff table that match the specified arbitrary SQL statement
	 */
	public Staff[] findByDynamicWhere(String sql, Object[] sqlParams) throws StaffDaoException;

}
