/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc;

import dao.*;
import factory.*;
import dto.*;
import exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class MentorMenteeDaoImpl extends AbstractDAO implements MentorMenteeDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT mentor_id, mentee_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( mentor_id, mentee_id ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET mentor_id = ?, mentee_id = ? WHERE mentor_id = ? AND mentee_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE mentor_id = ? AND mentee_id = ?";

	/** 
	 * Index of column mentor_id
	 */
	protected static final int COLUMN_MENTOR_ID = 1;

	/** 
	 * Index of column mentee_id
	 */
	protected static final int COLUMN_MENTEE_ID = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column mentor_id
	 */
	protected static final int PK_COLUMN_MENTOR_ID = 1;

	/** 
	 * Index of primary-key column mentee_id
	 */
	protected static final int PK_COLUMN_MENTEE_ID = 2;

	/** 
	 * Inserts a new row in the mentor_mentee table.
	 */
	public MentorMenteePk insert(MentorMentee dto) throws MentorMenteeDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getMentorId() );
			stmt.setInt( index++, dto.getMenteeId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MentorMenteeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the mentor_mentee table.
	 */
	public void update(MentorMenteePk pk, MentorMentee dto) throws MentorMenteeDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getMentorId() );
			stmt.setInt( index++, dto.getMenteeId() );
			stmt.setInt( 3, pk.getMentorId() );
			stmt.setInt( 4, pk.getMenteeId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MentorMenteeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the mentor_mentee table.
	 */
	public void delete(MentorMenteePk pk) throws MentorMenteeDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getMentorId() );
			stmt.setInt( 2, pk.getMenteeId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MentorMenteeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the mentor_mentee table that matches the specified primary-key value.
	 */
	public MentorMentee findByPrimaryKey(MentorMenteePk pk) throws MentorMenteeDaoException
	{
		return findByPrimaryKey( pk.getMentorId(), pk.getMenteeId() );
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria 'mentor_id = :mentorId AND mentee_id = :menteeId'.
	 */
	public MentorMentee findByPrimaryKey(int mentorId, int menteeId) throws MentorMenteeDaoException
	{
		MentorMentee ret[] = findByDynamicSelect( SQL_SELECT + " WHERE mentor_id = ? AND mentee_id = ?", new Object[] {  new Integer(mentorId),  new Integer(menteeId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria ''.
	 */
	public MentorMentee[] findAll() throws MentorMenteeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY mentor_id, mentee_id", null );
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria 'mentee_id = :menteeId'.
	 */
	public MentorMentee[] findByMentees(int menteeId) throws MentorMenteeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentee_id = ?", new Object[] {  new Integer(menteeId) } );
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria 'mentor_id = :mentorId'.
	 */
	public MentorMentee[] findByMentors(int mentorId) throws MentorMenteeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentor_id = ?", new Object[] {  new Integer(mentorId) } );
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria 'mentor_id = :mentorId'.
	 */
	public MentorMentee[] findWhereMentorIdEquals(int mentorId) throws MentorMenteeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentor_id = ? ORDER BY mentor_id", new Object[] {  new Integer(mentorId) } );
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the criteria 'mentee_id = :menteeId'.
	 */
	public MentorMentee[] findWhereMenteeIdEquals(int menteeId) throws MentorMenteeDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentee_id = ? ORDER BY mentee_id", new Object[] {  new Integer(menteeId) } );
	}

	/**
	 * Method 'MentorMenteeDaoImpl'
	 * 
	 */
	public MentorMenteeDaoImpl()
	{
	}

	/**
	 * Method 'MentorMenteeDaoImpl'
	 * 
	 * @param userConn
	 */
	public MentorMenteeDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "mentor_mentee";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected MentorMentee fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			MentorMentee dto = new MentorMentee();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected MentorMentee[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			MentorMentee dto = new MentorMentee();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		MentorMentee ret[] = new MentorMentee[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(MentorMentee dto, ResultSet rs) throws SQLException
	{
		dto.setMentorId( rs.getInt( COLUMN_MENTOR_ID ) );
		dto.setMenteeId( rs.getInt( COLUMN_MENTEE_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(MentorMentee dto)
	{
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the specified arbitrary SQL statement
	 */
	public MentorMentee[] findByDynamicSelect(String sql, Object[] sqlParams) throws MentorMenteeDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MentorMenteeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the mentor_mentee table that match the specified arbitrary SQL statement
	 */
	public MentorMentee[] findByDynamicWhere(String sql, Object[] sqlParams) throws MentorMenteeDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new MentorMenteeDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
