/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package jdbc;

import dao.*;
import factory.*;
import dto.*;
import exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class StaffDaoImpl extends AbstractDAO implements StaffDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT staff_id, full_name, login_name, password FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( staff_id, full_name, login_name, password ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET staff_id = ?, full_name = ?, login_name = ?, password = ? WHERE staff_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE staff_id = ?";

	/** 
	 * Index of column staff_id
	 */
	protected static final int COLUMN_STAFF_ID = 1;

	/** 
	 * Index of column full_name
	 */
	protected static final int COLUMN_FULL_NAME = 2;

	/** 
	 * Index of column login_name
	 */
	protected static final int COLUMN_LOGIN_NAME = 3;

	/** 
	 * Index of column password
	 */
	protected static final int COLUMN_PASSWORD = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column staff_id
	 */
	protected static final int PK_COLUMN_STAFF_ID = 1;

	/** 
	 * Inserts a new row in the staff table.
	 */
	public StaffPk insert(Staff dto) throws StaffDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getStaffId() );
			stmt.setString( index++, dto.getFullName() );
			stmt.setString( index++, dto.getLoginName() );
			stmt.setString( index++, dto.getPassword() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setStaffId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaffDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the staff table.
	 */
	public void update(StaffPk pk, Staff dto) throws StaffDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getStaffId() );
			stmt.setString( index++, dto.getFullName() );
			stmt.setString( index++, dto.getLoginName() );
			stmt.setString( index++, dto.getPassword() );
			stmt.setInt( 5, pk.getStaffId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaffDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the staff table.
	 */
	public void delete(StaffPk pk) throws StaffDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getStaffId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaffDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the staff table that matches the specified primary-key value.
	 */
	public Staff findByPrimaryKey(StaffPk pk) throws StaffDaoException
	{
		return findByPrimaryKey( pk.getStaffId() );
	}

	/** 
	 * Returns all rows from the staff table that match the criteria 'staff_id = :staffId'.
	 */
	public Staff findByPrimaryKey(int staffId) throws StaffDaoException
	{
		Staff ret[] = findByDynamicSelect( SQL_SELECT + " WHERE staff_id = ?", new Object[] {  new Integer(staffId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the staff table that match the criteria ''.
	 */
	public Staff[] findAll() throws StaffDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY staff_id", null );
	}

	/** 
	 * Returns all rows from the staff table that match the criteria 'staff_id = :staffId'.
	 */
	public Staff[] findWhereStaffIdEquals(int staffId) throws StaffDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE staff_id = ? ORDER BY staff_id", new Object[] {  new Integer(staffId) } );
	}

	/** 
	 * Returns all rows from the staff table that match the criteria 'full_name = :fullName'.
	 */
	public Staff[] findWhereFullNameEquals(String fullName) throws StaffDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE full_name = ? ORDER BY full_name", new Object[] { fullName } );
	}

	/** 
	 * Returns all rows from the staff table that match the criteria 'login_name = :loginName'.
	 */
	public Staff[] findWhereLoginNameEquals(String loginName) throws StaffDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE login_name = ? ORDER BY login_name", new Object[] { loginName } );
	}

	/** 
	 * Returns all rows from the staff table that match the criteria 'password = :password'.
	 */
	public Staff[] findWherePasswordEquals(String password) throws StaffDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE password = ? ORDER BY password", new Object[] { password } );
	}

	/**
	 * Method 'StaffDaoImpl'
	 * 
	 */
	public StaffDaoImpl()
	{
	}

	/**
	 * Method 'StaffDaoImpl'
	 * 
	 * @param userConn
	 */
	public StaffDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "staff";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Staff fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Staff dto = new Staff();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Staff[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Staff dto = new Staff();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Staff ret[] = new Staff[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Staff dto, ResultSet rs) throws SQLException
	{
		dto.setStaffId( rs.getInt( COLUMN_STAFF_ID ) );
		dto.setFullName( rs.getString( COLUMN_FULL_NAME ) );
		dto.setLoginName( rs.getString( COLUMN_LOGIN_NAME ) );
		dto.setPassword( rs.getString( COLUMN_PASSWORD ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Staff dto)
	{
	}

	/** 
	 * Returns all rows from the staff table that match the specified arbitrary SQL statement
	 */
	public Staff[] findByDynamicSelect(String sql, Object[] sqlParams) throws StaffDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaffDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the staff table that match the specified arbitrary SQL statement
	 */
	public Staff[] findByDynamicWhere(String sql, Object[] sqlParams) throws StaffDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new StaffDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
