/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dto;

import dao.*;
import exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Forms implements Serializable
{
	/** 
	 * This attribute maps to the column form_id in the forms table.
	 */
	protected int formId;

	/** 
	 * This attribute maps to the column mentor_id in the forms table.
	 */
	protected int mentorId;

	/** 
	 * This attribute maps to the column mentee_id in the forms table.
	 */
	protected int menteeId;

	/** 
	 * This attribute maps to the column meeting_time in the forms table.
	 */
	protected Date meetingTime;

	/** 
	 * This attribute maps to the column meeting_place in the forms table.
	 */
	protected String meetingPlace;

	/** 
	 * This attribute maps to the column ending_time in the forms table.
	 */
	protected Date endingTime;

	/** 
	 * This attribute maps to the column pre_planned_purpose in the forms table.
	 */
	protected String prePlannedPurpose;

	/** 
	 * This attribute maps to the column topic_activities in the forms table.
	 */
	protected String topicActivities;

	/** 
	 * This attribute maps to the column accomplishment in the forms table.
	 */
	protected String accomplishment;

	/** 
	 * This attribute maps to the column goals_nextmeeting in the forms table.
	 */
	protected String goalsNextmeeting;

	/** 
	 * This attribute maps to the column mentees_next_meeting in the forms table.
	 */
	protected String menteesNextMeeting;

	/** 
	 * This attribute maps to the column mentors_next_meeting in the forms table.
	 */
	protected String mentorsNextMeeting;

	/** 
	 * This attribute maps to the column time_next_meeting in the forms table.
	 */
	protected Date timeNextMeeting;

	/** 
	 * This attribute maps to the column place_next_meeting in the forms table.
	 */
	protected String placeNextMeeting;

	/**
	 * Method 'Forms'
	 * 
	 */
	public Forms()
	{
	}

	/**
	 * Method 'getFormId'
	 * 
	 * @return int
	 */
	public int getFormId()
	{
		return formId;
	}

	/**
	 * Method 'setFormId'
	 * 
	 * @param formId
	 */
	public void setFormId(int formId)
	{
		this.formId = formId;
	}

	/**
	 * Method 'getMentorId'
	 * 
	 * @return int
	 */
	public int getMentorId()
	{
		return mentorId;
	}

	/**
	 * Method 'setMentorId'
	 * 
	 * @param mentorId
	 */
	public void setMentorId(int mentorId)
	{
		this.mentorId = mentorId;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'getMeetingTime'
	 * 
	 * @return Date
	 */
	public Date getMeetingTime()
	{
		return meetingTime;
	}

	/**
	 * Method 'setMeetingTime'
	 * 
	 * @param meetingTime
	 */
	public void setMeetingTime(Date meetingTime)
	{
		this.meetingTime = meetingTime;
	}

	/**
	 * Method 'getMeetingPlace'
	 * 
	 * @return String
	 */
	public String getMeetingPlace()
	{
		return meetingPlace;
	}

	/**
	 * Method 'setMeetingPlace'
	 * 
	 * @param meetingPlace
	 */
	public void setMeetingPlace(String meetingPlace)
	{
		this.meetingPlace = meetingPlace;
	}

	/**
	 * Method 'getEndingTime'
	 * 
	 * @return Date
	 */
	public Date getEndingTime()
	{
		return endingTime;
	}

	/**
	 * Method 'setEndingTime'
	 * 
	 * @param endingTime
	 */
	public void setEndingTime(Date endingTime)
	{
		this.endingTime = endingTime;
	}

	/**
	 * Method 'getPrePlannedPurpose'
	 * 
	 * @return String
	 */
	public String getPrePlannedPurpose()
	{
		return prePlannedPurpose;
	}

	/**
	 * Method 'setPrePlannedPurpose'
	 * 
	 * @param prePlannedPurpose
	 */
	public void setPrePlannedPurpose(String prePlannedPurpose)
	{
		this.prePlannedPurpose = prePlannedPurpose;
	}

	/**
	 * Method 'getTopicActivities'
	 * 
	 * @return String
	 */
	public String getTopicActivities()
	{
		return topicActivities;
	}

	/**
	 * Method 'setTopicActivities'
	 * 
	 * @param topicActivities
	 */
	public void setTopicActivities(String topicActivities)
	{
		this.topicActivities = topicActivities;
	}

	/**
	 * Method 'getAccomplishment'
	 * 
	 * @return String
	 */
	public String getAccomplishment()
	{
		return accomplishment;
	}

	/**
	 * Method 'setAccomplishment'
	 * 
	 * @param accomplishment
	 */
	public void setAccomplishment(String accomplishment)
	{
		this.accomplishment = accomplishment;
	}

	/**
	 * Method 'getGoalsNextmeeting'
	 * 
	 * @return String
	 */
	public String getGoalsNextmeeting()
	{
		return goalsNextmeeting;
	}

	/**
	 * Method 'setGoalsNextmeeting'
	 * 
	 * @param goalsNextmeeting
	 */
	public void setGoalsNextmeeting(String goalsNextmeeting)
	{
		this.goalsNextmeeting = goalsNextmeeting;
	}

	/**
	 * Method 'getMenteesNextMeeting'
	 * 
	 * @return String
	 */
	public String getMenteesNextMeeting()
	{
		return menteesNextMeeting;
	}

	/**
	 * Method 'setMenteesNextMeeting'
	 * 
	 * @param menteesNextMeeting
	 */
	public void setMenteesNextMeeting(String menteesNextMeeting)
	{
		this.menteesNextMeeting = menteesNextMeeting;
	}

	/**
	 * Method 'getMentorsNextMeeting'
	 * 
	 * @return String
	 */
	public String getMentorsNextMeeting()
	{
		return mentorsNextMeeting;
	}

	/**
	 * Method 'setMentorsNextMeeting'
	 * 
	 * @param mentorsNextMeeting
	 */
	public void setMentorsNextMeeting(String mentorsNextMeeting)
	{
		this.mentorsNextMeeting = mentorsNextMeeting;
	}

	/**
	 * Method 'getTimeNextMeeting'
	 * 
	 * @return Date
	 */
	public Date getTimeNextMeeting()
	{
		return timeNextMeeting;
	}

	/**
	 * Method 'setTimeNextMeeting'
	 * 
	 * @param timeNextMeeting
	 */
	public void setTimeNextMeeting(Date timeNextMeeting)
	{
		this.timeNextMeeting = timeNextMeeting;
	}

	/**
	 * Method 'getPlaceNextMeeting'
	 * 
	 * @return String
	 */
	public String getPlaceNextMeeting()
	{
		return placeNextMeeting;
	}

	/**
	 * Method 'setPlaceNextMeeting'
	 * 
	 * @param placeNextMeeting
	 */
	public void setPlaceNextMeeting(String placeNextMeeting)
	{
		this.placeNextMeeting = placeNextMeeting;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Forms)) {
			return false;
		}
		
		final Forms _cast = (Forms) _other;
		if (formId != _cast.formId) {
			return false;
		}
		
		if (mentorId != _cast.mentorId) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (meetingTime == null ? _cast.meetingTime != meetingTime : !meetingTime.equals( _cast.meetingTime )) {
			return false;
		}
		
		if (meetingPlace == null ? _cast.meetingPlace != meetingPlace : !meetingPlace.equals( _cast.meetingPlace )) {
			return false;
		}
		
		if (endingTime == null ? _cast.endingTime != endingTime : !endingTime.equals( _cast.endingTime )) {
			return false;
		}
		
		if (prePlannedPurpose == null ? _cast.prePlannedPurpose != prePlannedPurpose : !prePlannedPurpose.equals( _cast.prePlannedPurpose )) {
			return false;
		}
		
		if (topicActivities == null ? _cast.topicActivities != topicActivities : !topicActivities.equals( _cast.topicActivities )) {
			return false;
		}
		
		if (accomplishment == null ? _cast.accomplishment != accomplishment : !accomplishment.equals( _cast.accomplishment )) {
			return false;
		}
		
		if (goalsNextmeeting == null ? _cast.goalsNextmeeting != goalsNextmeeting : !goalsNextmeeting.equals( _cast.goalsNextmeeting )) {
			return false;
		}
		
		if (menteesNextMeeting == null ? _cast.menteesNextMeeting != menteesNextMeeting : !menteesNextMeeting.equals( _cast.menteesNextMeeting )) {
			return false;
		}
		
		if (mentorsNextMeeting == null ? _cast.mentorsNextMeeting != mentorsNextMeeting : !mentorsNextMeeting.equals( _cast.mentorsNextMeeting )) {
			return false;
		}
		
		if (timeNextMeeting == null ? _cast.timeNextMeeting != timeNextMeeting : !timeNextMeeting.equals( _cast.timeNextMeeting )) {
			return false;
		}
		
		if (placeNextMeeting == null ? _cast.placeNextMeeting != placeNextMeeting : !placeNextMeeting.equals( _cast.placeNextMeeting )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + formId;
		_hashCode = 29 * _hashCode + mentorId;
		_hashCode = 29 * _hashCode + menteeId;
		if (meetingTime != null) {
			_hashCode = 29 * _hashCode + meetingTime.hashCode();
		}
		
		if (meetingPlace != null) {
			_hashCode = 29 * _hashCode + meetingPlace.hashCode();
		}
		
		if (endingTime != null) {
			_hashCode = 29 * _hashCode + endingTime.hashCode();
		}
		
		if (prePlannedPurpose != null) {
			_hashCode = 29 * _hashCode + prePlannedPurpose.hashCode();
		}
		
		if (topicActivities != null) {
			_hashCode = 29 * _hashCode + topicActivities.hashCode();
		}
		
		if (accomplishment != null) {
			_hashCode = 29 * _hashCode + accomplishment.hashCode();
		}
		
		if (goalsNextmeeting != null) {
			_hashCode = 29 * _hashCode + goalsNextmeeting.hashCode();
		}
		
		if (menteesNextMeeting != null) {
			_hashCode = 29 * _hashCode + menteesNextMeeting.hashCode();
		}
		
		if (mentorsNextMeeting != null) {
			_hashCode = 29 * _hashCode + mentorsNextMeeting.hashCode();
		}
		
		if (timeNextMeeting != null) {
			_hashCode = 29 * _hashCode + timeNextMeeting.hashCode();
		}
		
		if (placeNextMeeting != null) {
			_hashCode = 29 * _hashCode + placeNextMeeting.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FormsPk
	 */
	public FormsPk createPk()
	{
		return new FormsPk(formId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Forms: " );
		ret.append( "formId=" + formId );
		ret.append( ", mentorId=" + mentorId );
		ret.append( ", menteeId=" + menteeId );
		ret.append( ", meetingTime=" + meetingTime );
		ret.append( ", meetingPlace=" + meetingPlace );
		ret.append( ", endingTime=" + endingTime );
		ret.append( ", prePlannedPurpose=" + prePlannedPurpose );
		ret.append( ", topicActivities=" + topicActivities );
		ret.append( ", accomplishment=" + accomplishment );
		ret.append( ", goalsNextmeeting=" + goalsNextmeeting );
		ret.append( ", menteesNextMeeting=" + menteesNextMeeting );
		ret.append( ", mentorsNextMeeting=" + mentorsNextMeeting );
		ret.append( ", timeNextMeeting=" + timeNextMeeting );
		ret.append( ", placeNextMeeting=" + placeNextMeeting );
		return ret.toString();
	}

}
