/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dto;

import dao.*;

import exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Mentees implements Serializable
{
	/** 
	 * This attribute maps to the column mentee_id in the mentees table.
	 */
	protected int menteeId;

	/** 
	 * This attribute maps to the column first_name in the mentees table.
	 */
	protected String firstName;

	/** 
	 * This attribute maps to the column last_name in the mentees table.
	 */
	protected String lastName;

	/** 
	 * This attribute maps to the column SSN in the mentees table.
	 */
	protected String ssn;

	/** 
	 * This attribute maps to the column sex in the mentees table.
	 */
	protected String sex;

	/** 
	 * This attribute maps to the column age in the mentees table.
	 */
	protected int age;

	/** 
	 * This attribute represents whether the primitive attribute age is null.
	 */
	protected boolean ageNull = true;

	/** 
	 * This attribute maps to the column maritial_status in the mentees table.
	 */
	protected String maritialStatus;

	/** 
	 * This attribute maps to the column address in the mentees table.
	 */
	protected String address;

	/** 
	 * This attribute maps to the column zipcode in the mentees table.
	 */
	protected String zipcode;

	/** 
	 * This attribute maps to the column highest_education_level in the mentees table.
	 */
	protected String highestEducationLevel;

	/**
	 * Method 'Mentees'
	 * 
	 */
	public Mentees()
	{
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'getFirstName'
	 * 
	 * @return String
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Method 'setFirstName'
	 * 
	 * @param firstName
	 */
	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	/**
	 * Method 'getLastName'
	 * 
	 * @return String
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Method 'setLastName'
	 * 
	 * @param lastName
	 */
	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	/**
	 * Method 'getSsn'
	 * 
	 * @return String
	 */
	public String getSsn()
	{
		return ssn;
	}

	/**
	 * Method 'setSsn'
	 * 
	 * @param ssn
	 */
	public void setSsn(String ssn)
	{
		this.ssn = ssn;
	}

	/**
	 * Method 'getSex'
	 * 
	 * @return String
	 */
	public String getSex()
	{
		return sex;
	}

	/**
	 * Method 'setSex'
	 * 
	 * @param sex
	 */
	public void setSex(String sex)
	{
		this.sex = sex;
	}

	/**
	 * Method 'getAge'
	 * 
	 * @return int
	 */
	public int getAge()
	{
		return age;
	}

	/**
	 * Method 'setAge'
	 * 
	 * @param age
	 */
	public void setAge(int age)
	{
		this.age = age;
		this.ageNull = false;
	}

	/**
	 * Method 'setAgeNull'
	 * 
	 * @param value
	 */
	public void setAgeNull(boolean value)
	{
		this.ageNull = value;
	}

	/**
	 * Method 'isAgeNull'
	 * 
	 * @return boolean
	 */
	public boolean isAgeNull()
	{
		return ageNull;
	}

	/**
	 * Method 'getMaritialStatus'
	 * 
	 * @return String
	 */
	public String getMaritialStatus()
	{
		return maritialStatus;
	}

	/**
	 * Method 'setMaritialStatus'
	 * 
	 * @param maritialStatus
	 */
	public void setMaritialStatus(String maritialStatus)
	{
		this.maritialStatus = maritialStatus;
	}

	/**
	 * Method 'getAddress'
	 * 
	 * @return String
	 */
	public String getAddress()
	{
		return address;
	}

	/**
	 * Method 'setAddress'
	 * 
	 * @param address
	 */
	public void setAddress(String address)
	{
		this.address = address;
	}

	/**
	 * Method 'getZipcode'
	 * 
	 * @return String
	 */
	public String getZipcode()
	{
		return zipcode;
	}

	/**
	 * Method 'setZipcode'
	 * 
	 * @param zipcode
	 */
	public void setZipcode(String zipcode)
	{
		this.zipcode = zipcode;
	}

	/**
	 * Method 'getHighestEducationLevel'
	 * 
	 * @return String
	 */
	public String getHighestEducationLevel()
	{
		return highestEducationLevel;
	}

	/**
	 * Method 'setHighestEducationLevel'
	 * 
	 * @param highestEducationLevel
	 */
	public void setHighestEducationLevel(String highestEducationLevel)
	{
		this.highestEducationLevel = highestEducationLevel;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Mentees)) {
			return false;
		}
		
		final Mentees _cast = (Mentees) _other;
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (firstName == null ? _cast.firstName != firstName : !firstName.equals( _cast.firstName )) {
			return false;
		}
		
		if (lastName == null ? _cast.lastName != lastName : !lastName.equals( _cast.lastName )) {
			return false;
		}
		
		if (ssn == null ? _cast.ssn != ssn : !ssn.equals( _cast.ssn )) {
			return false;
		}
		
		if (sex == null ? _cast.sex != sex : !sex.equals( _cast.sex )) {
			return false;
		}
		
		if (age != _cast.age) {
			return false;
		}
		
		if (ageNull != _cast.ageNull) {
			return false;
		}
		
		if (maritialStatus == null ? _cast.maritialStatus != maritialStatus : !maritialStatus.equals( _cast.maritialStatus )) {
			return false;
		}
		
		if (address == null ? _cast.address != address : !address.equals( _cast.address )) {
			return false;
		}
		
		if (zipcode == null ? _cast.zipcode != zipcode : !zipcode.equals( _cast.zipcode )) {
			return false;
		}
		
		if (highestEducationLevel == null ? _cast.highestEducationLevel != highestEducationLevel : !highestEducationLevel.equals( _cast.highestEducationLevel )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + menteeId;
		if (firstName != null) {
			_hashCode = 29 * _hashCode + firstName.hashCode();
		}
		
		if (lastName != null) {
			_hashCode = 29 * _hashCode + lastName.hashCode();
		}
		
		if (ssn != null) {
			_hashCode = 29 * _hashCode + ssn.hashCode();
		}
		
		if (sex != null) {
			_hashCode = 29 * _hashCode + sex.hashCode();
		}
		
		_hashCode = 29 * _hashCode + age;
		_hashCode = 29 * _hashCode + (ageNull ? 1 : 0);
		if (maritialStatus != null) {
			_hashCode = 29 * _hashCode + maritialStatus.hashCode();
		}
		
		if (address != null) {
			_hashCode = 29 * _hashCode + address.hashCode();
		}
		
		if (zipcode != null) {
			_hashCode = 29 * _hashCode + zipcode.hashCode();
		}
		
		if (highestEducationLevel != null) {
			_hashCode = 29 * _hashCode + highestEducationLevel.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MenteesPk
	 */
	public MenteesPk createPk()
	{
		return new MenteesPk(menteeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Mentees: " );
		ret.append( "menteeId=" + menteeId );
		ret.append( ", firstName=" + firstName );
		ret.append( ", lastName=" + lastName );
		ret.append( ", ssn=" + ssn );
		ret.append( ", sex=" + sex );
		ret.append( ", age=" + age );
		ret.append( ", maritialStatus=" + maritialStatus );
		ret.append( ", address=" + address );
		ret.append( ", zipcode=" + zipcode );
		ret.append( ", highestEducationLevel=" + highestEducationLevel );
		return ret.toString();
	}

}
