/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dto;

import dao.*;
import factory.*;
import exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Staff implements Serializable
{
	/** 
	 * This attribute maps to the column staff_id in the staff table.
	 */
	protected int staffId;

	/** 
	 * This attribute maps to the column full_name in the staff table.
	 */
	protected String fullName;

	/** 
	 * This attribute maps to the column login_name in the staff table.
	 */
	protected String loginName;

	/** 
	 * This attribute maps to the column password in the staff table.
	 */
	protected String password;

	/**
	 * Method 'Staff'
	 * 
	 */
	public Staff()
	{
	}

	/**
	 * Method 'getStaffId'
	 * 
	 * @return int
	 */
	public int getStaffId()
	{
		return staffId;
	}

	/**
	 * Method 'setStaffId'
	 * 
	 * @param staffId
	 */
	public void setStaffId(int staffId)
	{
		this.staffId = staffId;
	}

	/**
	 * Method 'getFullName'
	 * 
	 * @return String
	 */
	public String getFullName()
	{
		return fullName;
	}

	/**
	 * Method 'setFullName'
	 * 
	 * @param fullName
	 */
	public void setFullName(String fullName)
	{
		this.fullName = fullName;
	}

	/**
	 * Method 'getLoginName'
	 * 
	 * @return String
	 */
	public String getLoginName()
	{
		return loginName;
	}

	/**
	 * Method 'setLoginName'
	 * 
	 * @param loginName
	 */
	public void setLoginName(String loginName)
	{
		this.loginName = loginName;
	}

	/**
	 * Method 'getPassword'
	 * 
	 * @return String
	 */
	public String getPassword()
	{
		return password;
	}

	/**
	 * Method 'setPassword'
	 * 
	 * @param password
	 */
	public void setPassword(String password)
	{
		this.password = password;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Staff)) {
			return false;
		}
		
		final Staff _cast = (Staff) _other;
		if (staffId != _cast.staffId) {
			return false;
		}
		
		if (fullName == null ? _cast.fullName != fullName : !fullName.equals( _cast.fullName )) {
			return false;
		}
		
		if (loginName == null ? _cast.loginName != loginName : !loginName.equals( _cast.loginName )) {
			return false;
		}
		
		if (password == null ? _cast.password != password : !password.equals( _cast.password )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + staffId;
		if (fullName != null) {
			_hashCode = 29 * _hashCode + fullName.hashCode();
		}
		
		if (loginName != null) {
			_hashCode = 29 * _hashCode + loginName.hashCode();
		}
		
		if (password != null) {
			_hashCode = 29 * _hashCode + password.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StaffPk
	 */
	public StaffPk createPk()
	{
		return new StaffPk(staffId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "dto.Staff: " );
		ret.append( "staffId=" + staffId );
		ret.append( ", fullName=" + fullName );
		ret.append( ", loginName=" + loginName );
		ret.append( ", password=" + password );
		return ret.toString();
	}

}
