/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.factory;

import java.sql.Connection;
import careownership.dao.*;
import careownership.jdbc.*;

public class DebtChangeDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return DebtChangeDao
	 */
	public static DebtChangeDao create()
	{
		return new DebtChangeDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return DebtChangeDao
	 */
	public static DebtChangeDao create(Connection conn)
	{
		return new DebtChangeDaoImpl( conn );
	}

}
