/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.factory;

import java.sql.Connection;
import careownership.dao.*;
import careownership.jdbc.*;

public class HouseholdInfoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return HouseholdInfoDao
	 */
	public static HouseholdInfoDao create()
	{
		return new HouseholdInfoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return HouseholdInfoDao
	 */
	public static HouseholdInfoDao create(Connection conn)
	{
		return new HouseholdInfoDaoImpl( conn );
	}

}
