/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.factory;

import java.sql.Connection;
import careownership.dao.*;
import careownership.jdbc.*;

public class MenteesDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return MenteesDao
	 */
	public static MenteesDao create()
	{
		return new MenteesDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return MenteesDao
	 */
	public static MenteesDao create(Connection conn)
	{
		return new MenteesDaoImpl( conn );
	}

}
