/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Application implements Serializable
{
	/** 
	 * This attribute maps to the column mentee_id in the application table.
	 */
	protected int menteeId;

	/** 
	 * This attribute maps to the column contact_type in the application table.
	 */
	protected String contactType;

	/** 
	 * This attribute maps to the column initial_contact_made in the application table.
	 */
	protected String initialContactMade;

	/** 
	 * This attribute maps to the column application_highest_education_level in the application table.
	 */
	protected String applicationHighestEducationLevel;

	/** 
	 * This attribute maps to the column drug_abuse_history in the application table.
	 */
	protected String drugAbuseHistory;

	/** 
	 * This attribute maps to the column drug_abuse_history_description in the application table.
	 */
	protected String drugAbuseHistoryDescription;

	/** 
	 * This attribute maps to the column homeless_history in the application table.
	 */
	protected String homelessHistory;

	/** 
	 * This attribute maps to the column homeless_history_description in the application table.
	 */
	protected String homelessHistoryDescription;

	/** 
	 * This attribute maps to the column alcohol_abuse_history in the application table.
	 */
	protected String alcoholAbuseHistory;

	/** 
	 * This attribute maps to the column alcohol_abuse_history_description in the application table.
	 */
	protected String alcoholAbuseHistoryDescription;

	/** 
	 * This attribute maps to the column religious_background in the application table.
	 */
	protected String religiousBackground;

	/** 
	 * This attribute maps to the column mental_illness_history in the application table.
	 */
	protected String mentalIllnessHistory;

	/** 
	 * This attribute maps to the column mental_illness_history_description in the application table.
	 */
	protected String mentalIllnessHistoryDescription;

	/** 
	 * This attribute maps to the column criminal_history in the application table.
	 */
	protected String criminalHistory;

	/** 
	 * This attribute maps to the column criminal_history_description in the application table.
	 */
	protected String criminalHistoryDescription;

	/** 
	 * This attribute maps to the column date_of_most_recent_criminal_offence in the application table.
	 */
	protected Date dateOfMostRecentCriminalOffence;

	/** 
	 * This attribute maps to the column probation_end_date in the application table.
	 */
	protected Date probationEndDate;

	/** 
	 * This attribute maps to the column other_initial_conditions in the application table.
	 */
	protected String otherInitialConditions;

	/** 
	 * This attribute maps to the column application_notes in the application table.
	 */
	protected String applicationNotes;

	/** 
	 * This attribute maps to the column application_received_date in the application table.
	 */
	protected Date applicationReceivedDate;

	/** 
	 * This attribute maps to the column application_recieved_method in the application table.
	 */
	protected String applicationRecievedMethod;

	/** 
	 * This attribute maps to the column previous_home_ownership in the application table.
	 */
	protected String previousHomeOwnership;

	/** 
	 * This attribute maps to the column application_status in the application table.
	 */
	protected String applicationStatus;

	/** 
	 * This attribute maps to the column interview_description in the application table.
	 */
	protected String interviewDescription;

	/** 
	 * This attribute maps to the column application_approved_date in the application table.
	 */
	protected Date applicationApprovedDate;

	/** 
	 * This attribute maps to the column date_begins_program in the application table.
	 */
	protected Date dateBeginsProgram;

	/** 
	 * This attribute maps to the column application_reference in the application table.
	 */
	protected String applicationReference;

	/** 
	 * This attribute maps to the column application_reference_affliation in the application table.
	 */
	protected String applicationReferenceAffliation;

	/** 
	 * This attribute maps to the column application_reference_contact_info in the application table.
	 */
	protected String applicationReferenceContactInfo;

	/**
	 * Method 'Application'
	 * 
	 */
	public Application()
	{
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'getContactType'
	 * 
	 * @return String
	 */
	public String getContactType()
	{
		return contactType;
	}

	/**
	 * Method 'setContactType'
	 * 
	 * @param contactType
	 */
	public void setContactType(String contactType)
	{
		this.contactType = contactType;
	}

	/**
	 * Method 'getInitialContactMade'
	 * 
	 * @return String
	 */
	public String getInitialContactMade()
	{
		return initialContactMade;
	}

	/**
	 * Method 'setInitialContactMade'
	 * 
	 * @param initialContactMade
	 */
	public void setInitialContactMade(String initialContactMade)
	{
		this.initialContactMade = initialContactMade;
	}

	/**
	 * Method 'getApplicationHighestEducationLevel'
	 * 
	 * @return String
	 */
	public String getApplicationHighestEducationLevel()
	{
		return applicationHighestEducationLevel;
	}

	/**
	 * Method 'setApplicationHighestEducationLevel'
	 * 
	 * @param applicationHighestEducationLevel
	 */
	public void setApplicationHighestEducationLevel(String applicationHighestEducationLevel)
	{
		this.applicationHighestEducationLevel = applicationHighestEducationLevel;
	}

	/**
	 * Method 'getDrugAbuseHistory'
	 * 
	 * @return String
	 */
	public String getDrugAbuseHistory()
	{
		return drugAbuseHistory;
	}

	/**
	 * Method 'setDrugAbuseHistory'
	 * 
	 * @param drugAbuseHistory
	 */
	public void setDrugAbuseHistory(String drugAbuseHistory)
	{
		this.drugAbuseHistory = drugAbuseHistory;
	}

	/**
	 * Method 'getDrugAbuseHistoryDescription'
	 * 
	 * @return String
	 */
	public String getDrugAbuseHistoryDescription()
	{
		return drugAbuseHistoryDescription;
	}

	/**
	 * Method 'setDrugAbuseHistoryDescription'
	 * 
	 * @param drugAbuseHistoryDescription
	 */
	public void setDrugAbuseHistoryDescription(String drugAbuseHistoryDescription)
	{
		this.drugAbuseHistoryDescription = drugAbuseHistoryDescription;
	}

	/**
	 * Method 'getHomelessHistory'
	 * 
	 * @return String
	 */
	public String getHomelessHistory()
	{
		return homelessHistory;
	}

	/**
	 * Method 'setHomelessHistory'
	 * 
	 * @param homelessHistory
	 */
	public void setHomelessHistory(String homelessHistory)
	{
		this.homelessHistory = homelessHistory;
	}

	/**
	 * Method 'getHomelessHistoryDescription'
	 * 
	 * @return String
	 */
	public String getHomelessHistoryDescription()
	{
		return homelessHistoryDescription;
	}

	/**
	 * Method 'setHomelessHistoryDescription'
	 * 
	 * @param homelessHistoryDescription
	 */
	public void setHomelessHistoryDescription(String homelessHistoryDescription)
	{
		this.homelessHistoryDescription = homelessHistoryDescription;
	}

	/**
	 * Method 'getAlcoholAbuseHistory'
	 * 
	 * @return String
	 */
	public String getAlcoholAbuseHistory()
	{
		return alcoholAbuseHistory;
	}

	/**
	 * Method 'setAlcoholAbuseHistory'
	 * 
	 * @param alcoholAbuseHistory
	 */
	public void setAlcoholAbuseHistory(String alcoholAbuseHistory)
	{
		this.alcoholAbuseHistory = alcoholAbuseHistory;
	}

	/**
	 * Method 'getAlcoholAbuseHistoryDescription'
	 * 
	 * @return String
	 */
	public String getAlcoholAbuseHistoryDescription()
	{
		return alcoholAbuseHistoryDescription;
	}

	/**
	 * Method 'setAlcoholAbuseHistoryDescription'
	 * 
	 * @param alcoholAbuseHistoryDescription
	 */
	public void setAlcoholAbuseHistoryDescription(String alcoholAbuseHistoryDescription)
	{
		this.alcoholAbuseHistoryDescription = alcoholAbuseHistoryDescription;
	}

	/**
	 * Method 'getReligiousBackground'
	 * 
	 * @return String
	 */
	public String getReligiousBackground()
	{
		return religiousBackground;
	}

	/**
	 * Method 'setReligiousBackground'
	 * 
	 * @param religiousBackground
	 */
	public void setReligiousBackground(String religiousBackground)
	{
		this.religiousBackground = religiousBackground;
	}

	/**
	 * Method 'getMentalIllnessHistory'
	 * 
	 * @return String
	 */
	public String getMentalIllnessHistory()
	{
		return mentalIllnessHistory;
	}

	/**
	 * Method 'setMentalIllnessHistory'
	 * 
	 * @param mentalIllnessHistory
	 */
	public void setMentalIllnessHistory(String mentalIllnessHistory)
	{
		this.mentalIllnessHistory = mentalIllnessHistory;
	}

	/**
	 * Method 'getMentalIllnessHistoryDescription'
	 * 
	 * @return String
	 */
	public String getMentalIllnessHistoryDescription()
	{
		return mentalIllnessHistoryDescription;
	}

	/**
	 * Method 'setMentalIllnessHistoryDescription'
	 * 
	 * @param mentalIllnessHistoryDescription
	 */
	public void setMentalIllnessHistoryDescription(String mentalIllnessHistoryDescription)
	{
		this.mentalIllnessHistoryDescription = mentalIllnessHistoryDescription;
	}

	/**
	 * Method 'getCriminalHistory'
	 * 
	 * @return String
	 */
	public String getCriminalHistory()
	{
		return criminalHistory;
	}

	/**
	 * Method 'setCriminalHistory'
	 * 
	 * @param criminalHistory
	 */
	public void setCriminalHistory(String criminalHistory)
	{
		this.criminalHistory = criminalHistory;
	}

	/**
	 * Method 'getCriminalHistoryDescription'
	 * 
	 * @return String
	 */
	public String getCriminalHistoryDescription()
	{
		return criminalHistoryDescription;
	}

	/**
	 * Method 'setCriminalHistoryDescription'
	 * 
	 * @param criminalHistoryDescription
	 */
	public void setCriminalHistoryDescription(String criminalHistoryDescription)
	{
		this.criminalHistoryDescription = criminalHistoryDescription;
	}

	/**
	 * Method 'getDateOfMostRecentCriminalOffence'
	 * 
	 * @return Date
	 */
	public Date getDateOfMostRecentCriminalOffence()
	{
		return dateOfMostRecentCriminalOffence;
	}

	/**
	 * Method 'setDateOfMostRecentCriminalOffence'
	 * 
	 * @param dateOfMostRecentCriminalOffence
	 */
	public void setDateOfMostRecentCriminalOffence(Date dateOfMostRecentCriminalOffence)
	{
		this.dateOfMostRecentCriminalOffence = dateOfMostRecentCriminalOffence;
	}

	/**
	 * Method 'getProbationEndDate'
	 * 
	 * @return Date
	 */
	public Date getProbationEndDate()
	{
		return probationEndDate;
	}

	/**
	 * Method 'setProbationEndDate'
	 * 
	 * @param probationEndDate
	 */
	public void setProbationEndDate(Date probationEndDate)
	{
		this.probationEndDate = probationEndDate;
	}

	/**
	 * Method 'getOtherInitialConditions'
	 * 
	 * @return String
	 */
	public String getOtherInitialConditions()
	{
		return otherInitialConditions;
	}

	/**
	 * Method 'setOtherInitialConditions'
	 * 
	 * @param otherInitialConditions
	 */
	public void setOtherInitialConditions(String otherInitialConditions)
	{
		this.otherInitialConditions = otherInitialConditions;
	}

	/**
	 * Method 'getApplicationNotes'
	 * 
	 * @return String
	 */
	public String getApplicationNotes()
	{
		return applicationNotes;
	}

	/**
	 * Method 'setApplicationNotes'
	 * 
	 * @param applicationNotes
	 */
	public void setApplicationNotes(String applicationNotes)
	{
		this.applicationNotes = applicationNotes;
	}

	/**
	 * Method 'getApplicationReceivedDate'
	 * 
	 * @return Date
	 */
	public Date getApplicationReceivedDate()
	{
		return applicationReceivedDate;
	}

	/**
	 * Method 'setApplicationReceivedDate'
	 * 
	 * @param applicationReceivedDate
	 */
	public void setApplicationReceivedDate(Date applicationReceivedDate)
	{
		this.applicationReceivedDate = applicationReceivedDate;
	}

	/**
	 * Method 'getApplicationRecievedMethod'
	 * 
	 * @return String
	 */
	public String getApplicationRecievedMethod()
	{
		return applicationRecievedMethod;
	}

	/**
	 * Method 'setApplicationRecievedMethod'
	 * 
	 * @param applicationRecievedMethod
	 */
	public void setApplicationRecievedMethod(String applicationRecievedMethod)
	{
		this.applicationRecievedMethod = applicationRecievedMethod;
	}

	/**
	 * Method 'getPreviousHomeOwnership'
	 * 
	 * @return String
	 */
	public String getPreviousHomeOwnership()
	{
		return previousHomeOwnership;
	}

	/**
	 * Method 'setPreviousHomeOwnership'
	 * 
	 * @param previousHomeOwnership
	 */
	public void setPreviousHomeOwnership(String previousHomeOwnership)
	{
		this.previousHomeOwnership = previousHomeOwnership;
	}

	/**
	 * Method 'getApplicationStatus'
	 * 
	 * @return String
	 */
	public String getApplicationStatus()
	{
		return applicationStatus;
	}

	/**
	 * Method 'setApplicationStatus'
	 * 
	 * @param applicationStatus
	 */
	public void setApplicationStatus(String applicationStatus)
	{
		this.applicationStatus = applicationStatus;
	}

	/**
	 * Method 'getInterviewDescription'
	 * 
	 * @return String
	 */
	public String getInterviewDescription()
	{
		return interviewDescription;
	}

	/**
	 * Method 'setInterviewDescription'
	 * 
	 * @param interviewDescription
	 */
	public void setInterviewDescription(String interviewDescription)
	{
		this.interviewDescription = interviewDescription;
	}

	/**
	 * Method 'getApplicationApprovedDate'
	 * 
	 * @return Date
	 */
	public Date getApplicationApprovedDate()
	{
		return applicationApprovedDate;
	}

	/**
	 * Method 'setApplicationApprovedDate'
	 * 
	 * @param applicationApprovedDate
	 */
	public void setApplicationApprovedDate(Date applicationApprovedDate)
	{
		this.applicationApprovedDate = applicationApprovedDate;
	}

	/**
	 * Method 'getDateBeginsProgram'
	 * 
	 * @return Date
	 */
	public Date getDateBeginsProgram()
	{
		return dateBeginsProgram;
	}

	/**
	 * Method 'setDateBeginsProgram'
	 * 
	 * @param dateBeginsProgram
	 */
	public void setDateBeginsProgram(Date dateBeginsProgram)
	{
		this.dateBeginsProgram = dateBeginsProgram;
	}

	/**
	 * Method 'getApplicationReference'
	 * 
	 * @return String
	 */
	public String getApplicationReference()
	{
		return applicationReference;
	}

	/**
	 * Method 'setApplicationReference'
	 * 
	 * @param applicationReference
	 */
	public void setApplicationReference(String applicationReference)
	{
		this.applicationReference = applicationReference;
	}

	/**
	 * Method 'getApplicationReferenceAffliation'
	 * 
	 * @return String
	 */
	public String getApplicationReferenceAffliation()
	{
		return applicationReferenceAffliation;
	}

	/**
	 * Method 'setApplicationReferenceAffliation'
	 * 
	 * @param applicationReferenceAffliation
	 */
	public void setApplicationReferenceAffliation(String applicationReferenceAffliation)
	{
		this.applicationReferenceAffliation = applicationReferenceAffliation;
	}

	/**
	 * Method 'getApplicationReferenceContactInfo'
	 * 
	 * @return String
	 */
	public String getApplicationReferenceContactInfo()
	{
		return applicationReferenceContactInfo;
	}

	/**
	 * Method 'setApplicationReferenceContactInfo'
	 * 
	 * @param applicationReferenceContactInfo
	 */
	public void setApplicationReferenceContactInfo(String applicationReferenceContactInfo)
	{
		this.applicationReferenceContactInfo = applicationReferenceContactInfo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Application)) {
			return false;
		}
		
		final Application _cast = (Application) _other;
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (contactType == null ? _cast.contactType != contactType : !contactType.equals( _cast.contactType )) {
			return false;
		}
		
		if (initialContactMade == null ? _cast.initialContactMade != initialContactMade : !initialContactMade.equals( _cast.initialContactMade )) {
			return false;
		}
		
		if (applicationHighestEducationLevel == null ? _cast.applicationHighestEducationLevel != applicationHighestEducationLevel : !applicationHighestEducationLevel.equals( _cast.applicationHighestEducationLevel )) {
			return false;
		}
		
		if (drugAbuseHistory == null ? _cast.drugAbuseHistory != drugAbuseHistory : !drugAbuseHistory.equals( _cast.drugAbuseHistory )) {
			return false;
		}
		
		if (drugAbuseHistoryDescription == null ? _cast.drugAbuseHistoryDescription != drugAbuseHistoryDescription : !drugAbuseHistoryDescription.equals( _cast.drugAbuseHistoryDescription )) {
			return false;
		}
		
		if (homelessHistory == null ? _cast.homelessHistory != homelessHistory : !homelessHistory.equals( _cast.homelessHistory )) {
			return false;
		}
		
		if (homelessHistoryDescription == null ? _cast.homelessHistoryDescription != homelessHistoryDescription : !homelessHistoryDescription.equals( _cast.homelessHistoryDescription )) {
			return false;
		}
		
		if (alcoholAbuseHistory == null ? _cast.alcoholAbuseHistory != alcoholAbuseHistory : !alcoholAbuseHistory.equals( _cast.alcoholAbuseHistory )) {
			return false;
		}
		
		if (alcoholAbuseHistoryDescription == null ? _cast.alcoholAbuseHistoryDescription != alcoholAbuseHistoryDescription : !alcoholAbuseHistoryDescription.equals( _cast.alcoholAbuseHistoryDescription )) {
			return false;
		}
		
		if (religiousBackground == null ? _cast.religiousBackground != religiousBackground : !religiousBackground.equals( _cast.religiousBackground )) {
			return false;
		}
		
		if (mentalIllnessHistory == null ? _cast.mentalIllnessHistory != mentalIllnessHistory : !mentalIllnessHistory.equals( _cast.mentalIllnessHistory )) {
			return false;
		}
		
		if (mentalIllnessHistoryDescription == null ? _cast.mentalIllnessHistoryDescription != mentalIllnessHistoryDescription : !mentalIllnessHistoryDescription.equals( _cast.mentalIllnessHistoryDescription )) {
			return false;
		}
		
		if (criminalHistory == null ? _cast.criminalHistory != criminalHistory : !criminalHistory.equals( _cast.criminalHistory )) {
			return false;
		}
		
		if (criminalHistoryDescription == null ? _cast.criminalHistoryDescription != criminalHistoryDescription : !criminalHistoryDescription.equals( _cast.criminalHistoryDescription )) {
			return false;
		}
		
		if (dateOfMostRecentCriminalOffence == null ? _cast.dateOfMostRecentCriminalOffence != dateOfMostRecentCriminalOffence : !dateOfMostRecentCriminalOffence.equals( _cast.dateOfMostRecentCriminalOffence )) {
			return false;
		}
		
		if (probationEndDate == null ? _cast.probationEndDate != probationEndDate : !probationEndDate.equals( _cast.probationEndDate )) {
			return false;
		}
		
		if (otherInitialConditions == null ? _cast.otherInitialConditions != otherInitialConditions : !otherInitialConditions.equals( _cast.otherInitialConditions )) {
			return false;
		}
		
		if (applicationNotes == null ? _cast.applicationNotes != applicationNotes : !applicationNotes.equals( _cast.applicationNotes )) {
			return false;
		}
		
		if (applicationReceivedDate == null ? _cast.applicationReceivedDate != applicationReceivedDate : !applicationReceivedDate.equals( _cast.applicationReceivedDate )) {
			return false;
		}
		
		if (applicationRecievedMethod == null ? _cast.applicationRecievedMethod != applicationRecievedMethod : !applicationRecievedMethod.equals( _cast.applicationRecievedMethod )) {
			return false;
		}
		
		if (previousHomeOwnership == null ? _cast.previousHomeOwnership != previousHomeOwnership : !previousHomeOwnership.equals( _cast.previousHomeOwnership )) {
			return false;
		}
		
		if (applicationStatus == null ? _cast.applicationStatus != applicationStatus : !applicationStatus.equals( _cast.applicationStatus )) {
			return false;
		}
		
		if (interviewDescription == null ? _cast.interviewDescription != interviewDescription : !interviewDescription.equals( _cast.interviewDescription )) {
			return false;
		}
		
		if (applicationApprovedDate == null ? _cast.applicationApprovedDate != applicationApprovedDate : !applicationApprovedDate.equals( _cast.applicationApprovedDate )) {
			return false;
		}
		
		if (dateBeginsProgram == null ? _cast.dateBeginsProgram != dateBeginsProgram : !dateBeginsProgram.equals( _cast.dateBeginsProgram )) {
			return false;
		}
		
		if (applicationReference == null ? _cast.applicationReference != applicationReference : !applicationReference.equals( _cast.applicationReference )) {
			return false;
		}
		
		if (applicationReferenceAffliation == null ? _cast.applicationReferenceAffliation != applicationReferenceAffliation : !applicationReferenceAffliation.equals( _cast.applicationReferenceAffliation )) {
			return false;
		}
		
		if (applicationReferenceContactInfo == null ? _cast.applicationReferenceContactInfo != applicationReferenceContactInfo : !applicationReferenceContactInfo.equals( _cast.applicationReferenceContactInfo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + menteeId;
		if (contactType != null) {
			_hashCode = 29 * _hashCode + contactType.hashCode();
		}
		
		if (initialContactMade != null) {
			_hashCode = 29 * _hashCode + initialContactMade.hashCode();
		}
		
		if (applicationHighestEducationLevel != null) {
			_hashCode = 29 * _hashCode + applicationHighestEducationLevel.hashCode();
		}
		
		if (drugAbuseHistory != null) {
			_hashCode = 29 * _hashCode + drugAbuseHistory.hashCode();
		}
		
		if (drugAbuseHistoryDescription != null) {
			_hashCode = 29 * _hashCode + drugAbuseHistoryDescription.hashCode();
		}
		
		if (homelessHistory != null) {
			_hashCode = 29 * _hashCode + homelessHistory.hashCode();
		}
		
		if (homelessHistoryDescription != null) {
			_hashCode = 29 * _hashCode + homelessHistoryDescription.hashCode();
		}
		
		if (alcoholAbuseHistory != null) {
			_hashCode = 29 * _hashCode + alcoholAbuseHistory.hashCode();
		}
		
		if (alcoholAbuseHistoryDescription != null) {
			_hashCode = 29 * _hashCode + alcoholAbuseHistoryDescription.hashCode();
		}
		
		if (religiousBackground != null) {
			_hashCode = 29 * _hashCode + religiousBackground.hashCode();
		}
		
		if (mentalIllnessHistory != null) {
			_hashCode = 29 * _hashCode + mentalIllnessHistory.hashCode();
		}
		
		if (mentalIllnessHistoryDescription != null) {
			_hashCode = 29 * _hashCode + mentalIllnessHistoryDescription.hashCode();
		}
		
		if (criminalHistory != null) {
			_hashCode = 29 * _hashCode + criminalHistory.hashCode();
		}
		
		if (criminalHistoryDescription != null) {
			_hashCode = 29 * _hashCode + criminalHistoryDescription.hashCode();
		}
		
		if (dateOfMostRecentCriminalOffence != null) {
			_hashCode = 29 * _hashCode + dateOfMostRecentCriminalOffence.hashCode();
		}
		
		if (probationEndDate != null) {
			_hashCode = 29 * _hashCode + probationEndDate.hashCode();
		}
		
		if (otherInitialConditions != null) {
			_hashCode = 29 * _hashCode + otherInitialConditions.hashCode();
		}
		
		if (applicationNotes != null) {
			_hashCode = 29 * _hashCode + applicationNotes.hashCode();
		}
		
		if (applicationReceivedDate != null) {
			_hashCode = 29 * _hashCode + applicationReceivedDate.hashCode();
		}
		
		if (applicationRecievedMethod != null) {
			_hashCode = 29 * _hashCode + applicationRecievedMethod.hashCode();
		}
		
		if (previousHomeOwnership != null) {
			_hashCode = 29 * _hashCode + previousHomeOwnership.hashCode();
		}
		
		if (applicationStatus != null) {
			_hashCode = 29 * _hashCode + applicationStatus.hashCode();
		}
		
		if (interviewDescription != null) {
			_hashCode = 29 * _hashCode + interviewDescription.hashCode();
		}
		
		if (applicationApprovedDate != null) {
			_hashCode = 29 * _hashCode + applicationApprovedDate.hashCode();
		}
		
		if (dateBeginsProgram != null) {
			_hashCode = 29 * _hashCode + dateBeginsProgram.hashCode();
		}
		
		if (applicationReference != null) {
			_hashCode = 29 * _hashCode + applicationReference.hashCode();
		}
		
		if (applicationReferenceAffliation != null) {
			_hashCode = 29 * _hashCode + applicationReferenceAffliation.hashCode();
		}
		
		if (applicationReferenceContactInfo != null) {
			_hashCode = 29 * _hashCode + applicationReferenceContactInfo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ApplicationPk
	 */
	public ApplicationPk createPk()
	{
		return new ApplicationPk(menteeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.Application: " );
		ret.append( "menteeId=" + menteeId );
		ret.append( ", contactType=" + contactType );
		ret.append( ", initialContactMade=" + initialContactMade );
		ret.append( ", applicationHighestEducationLevel=" + applicationHighestEducationLevel );
		ret.append( ", drugAbuseHistory=" + drugAbuseHistory );
		ret.append( ", drugAbuseHistoryDescription=" + drugAbuseHistoryDescription );
		ret.append( ", homelessHistory=" + homelessHistory );
		ret.append( ", homelessHistoryDescription=" + homelessHistoryDescription );
		ret.append( ", alcoholAbuseHistory=" + alcoholAbuseHistory );
		ret.append( ", alcoholAbuseHistoryDescription=" + alcoholAbuseHistoryDescription );
		ret.append( ", religiousBackground=" + religiousBackground );
		ret.append( ", mentalIllnessHistory=" + mentalIllnessHistory );
		ret.append( ", mentalIllnessHistoryDescription=" + mentalIllnessHistoryDescription );
		ret.append( ", criminalHistory=" + criminalHistory );
		ret.append( ", criminalHistoryDescription=" + criminalHistoryDescription );
		ret.append( ", dateOfMostRecentCriminalOffence=" + dateOfMostRecentCriminalOffence );
		ret.append( ", probationEndDate=" + probationEndDate );
		ret.append( ", otherInitialConditions=" + otherInitialConditions );
		ret.append( ", applicationNotes=" + applicationNotes );
		ret.append( ", applicationReceivedDate=" + applicationReceivedDate );
		ret.append( ", applicationRecievedMethod=" + applicationRecievedMethod );
		ret.append( ", previousHomeOwnership=" + previousHomeOwnership );
		ret.append( ", applicationStatus=" + applicationStatus );
		ret.append( ", interviewDescription=" + interviewDescription );
		ret.append( ", applicationApprovedDate=" + applicationApprovedDate );
		ret.append( ", dateBeginsProgram=" + dateBeginsProgram );
		ret.append( ", applicationReference=" + applicationReference );
		ret.append( ", applicationReferenceAffliation=" + applicationReferenceAffliation );
		ret.append( ", applicationReferenceContactInfo=" + applicationReferenceContactInfo );
		return ret.toString();
	}

}
