/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the application table.
 */
public class ApplicationPk implements Serializable
{
	protected int menteeId;

	/** 
	 * This attribute represents whether the primitive attribute menteeId is null.
	 */
	protected boolean menteeIdNull;

	/** 
	 * Sets the value of menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/** 
	 * Gets the value of menteeId
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'ApplicationPk'
	 * 
	 */
	public ApplicationPk()
	{
	}

	/**
	 * Method 'ApplicationPk'
	 * 
	 * @param menteeId
	 */
	public ApplicationPk(final int menteeId)
	{
		this.menteeId = menteeId;
	}

	/** 
	 * Sets the value of menteeIdNull
	 */
	public void setMenteeIdNull(boolean menteeIdNull)
	{
		this.menteeIdNull = menteeIdNull;
	}

	/** 
	 * Gets the value of menteeIdNull
	 */
	public boolean isMenteeIdNull()
	{
		return menteeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ApplicationPk)) {
			return false;
		}
		
		final ApplicationPk _cast = (ApplicationPk) _other;
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (menteeIdNull != _cast.menteeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + menteeId;
		_hashCode = 29 * _hashCode + (menteeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.ApplicationPk: " );
		ret.append( "menteeId=" + menteeId );
		return ret.toString();
	}

}
