/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the debt_change table.
 */
public class DebtChangePk implements Serializable
{
	protected int debtChangeId;

	/** 
	 * This attribute represents whether the primitive attribute debtChangeId is null.
	 */
	protected boolean debtChangeIdNull;

	/** 
	 * Sets the value of debtChangeId
	 */
	public void setDebtChangeId(int debtChangeId)
	{
		this.debtChangeId = debtChangeId;
	}

	/** 
	 * Gets the value of debtChangeId
	 */
	public int getDebtChangeId()
	{
		return debtChangeId;
	}

	/**
	 * Method 'DebtChangePk'
	 * 
	 */
	public DebtChangePk()
	{
	}

	/**
	 * Method 'DebtChangePk'
	 * 
	 * @param debtChangeId
	 */
	public DebtChangePk(final int debtChangeId)
	{
		this.debtChangeId = debtChangeId;
	}

	/** 
	 * Sets the value of debtChangeIdNull
	 */
	public void setDebtChangeIdNull(boolean debtChangeIdNull)
	{
		this.debtChangeIdNull = debtChangeIdNull;
	}

	/** 
	 * Gets the value of debtChangeIdNull
	 */
	public boolean isDebtChangeIdNull()
	{
		return debtChangeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DebtChangePk)) {
			return false;
		}
		
		final DebtChangePk _cast = (DebtChangePk) _other;
		if (debtChangeId != _cast.debtChangeId) {
			return false;
		}
		
		if (debtChangeIdNull != _cast.debtChangeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + debtChangeId;
		_hashCode = 29 * _hashCode + (debtChangeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.DebtChangePk: " );
		ret.append( "debtChangeId=" + debtChangeId );
		return ret.toString();
	}

}
