/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class DebtChange implements Serializable
{
	/** 
	 * This attribute maps to the column debt_change_id in the debt_change table.
	 */
	protected int debtChangeId;

	/** 
	 * This attribute maps to the column current_total_debt in the debt_change table.
	 */
	protected int currentTotalDebt;

	/** 
	 * This attribute represents whether the primitive attribute currentTotalDebt is null.
	 */
	protected boolean currentTotalDebtNull = true;

	/** 
	 * This attribute maps to the column current_debt_type in the debt_change table.
	 */
	protected String currentDebtType;

	/** 
	 * This attribute maps to the column current_debt_description in the debt_change table.
	 */
	protected String currentDebtDescription;

	/** 
	 * This attribute maps to the column current_debt_date in the debt_change table.
	 */
	protected Date currentDebtDate;

	/** 
	 * This attribute maps to the column mentee_id in the debt_change table.
	 */
	protected int menteeId;

	/**
	 * Method 'DebtChange'
	 * 
	 */
	public DebtChange()
	{
	}

	/**
	 * Method 'getDebtChangeId'
	 * 
	 * @return int
	 */
	public int getDebtChangeId()
	{
		return debtChangeId;
	}

	/**
	 * Method 'setDebtChangeId'
	 * 
	 * @param debtChangeId
	 */
	public void setDebtChangeId(int debtChangeId)
	{
		this.debtChangeId = debtChangeId;
	}

	/**
	 * Method 'getCurrentTotalDebt'
	 * 
	 * @return int
	 */
	public int getCurrentTotalDebt()
	{
		return currentTotalDebt;
	}

	/**
	 * Method 'setCurrentTotalDebt'
	 * 
	 * @param currentTotalDebt
	 */
	public void setCurrentTotalDebt(int currentTotalDebt)
	{
		this.currentTotalDebt = currentTotalDebt;
		this.currentTotalDebtNull = false;
	}

	/**
	 * Method 'setCurrentTotalDebtNull'
	 * 
	 * @param value
	 */
	public void setCurrentTotalDebtNull(boolean value)
	{
		this.currentTotalDebtNull = value;
	}

	/**
	 * Method 'isCurrentTotalDebtNull'
	 * 
	 * @return boolean
	 */
	public boolean isCurrentTotalDebtNull()
	{
		return currentTotalDebtNull;
	}

	/**
	 * Method 'getCurrentDebtType'
	 * 
	 * @return String
	 */
	public String getCurrentDebtType()
	{
		return currentDebtType;
	}

	/**
	 * Method 'setCurrentDebtType'
	 * 
	 * @param currentDebtType
	 */
	public void setCurrentDebtType(String currentDebtType)
	{
		this.currentDebtType = currentDebtType;
	}

	/**
	 * Method 'getCurrentDebtDescription'
	 * 
	 * @return String
	 */
	public String getCurrentDebtDescription()
	{
		return currentDebtDescription;
	}

	/**
	 * Method 'setCurrentDebtDescription'
	 * 
	 * @param currentDebtDescription
	 */
	public void setCurrentDebtDescription(String currentDebtDescription)
	{
		this.currentDebtDescription = currentDebtDescription;
	}

	/**
	 * Method 'getCurrentDebtDate'
	 * 
	 * @return Date
	 */
	public Date getCurrentDebtDate()
	{
		return currentDebtDate;
	}

	/**
	 * Method 'setCurrentDebtDate'
	 * 
	 * @param currentDebtDate
	 */
	public void setCurrentDebtDate(Date currentDebtDate)
	{
		this.currentDebtDate = currentDebtDate;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DebtChange)) {
			return false;
		}
		
		final DebtChange _cast = (DebtChange) _other;
		if (debtChangeId != _cast.debtChangeId) {
			return false;
		}
		
		if (currentTotalDebt != _cast.currentTotalDebt) {
			return false;
		}
		
		if (currentTotalDebtNull != _cast.currentTotalDebtNull) {
			return false;
		}
		
		if (currentDebtType == null ? _cast.currentDebtType != currentDebtType : !currentDebtType.equals( _cast.currentDebtType )) {
			return false;
		}
		
		if (currentDebtDescription == null ? _cast.currentDebtDescription != currentDebtDescription : !currentDebtDescription.equals( _cast.currentDebtDescription )) {
			return false;
		}
		
		if (currentDebtDate == null ? _cast.currentDebtDate != currentDebtDate : !currentDebtDate.equals( _cast.currentDebtDate )) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + debtChangeId;
		_hashCode = 29 * _hashCode + currentTotalDebt;
		_hashCode = 29 * _hashCode + (currentTotalDebtNull ? 1 : 0);
		if (currentDebtType != null) {
			_hashCode = 29 * _hashCode + currentDebtType.hashCode();
		}
		
		if (currentDebtDescription != null) {
			_hashCode = 29 * _hashCode + currentDebtDescription.hashCode();
		}
		
		if (currentDebtDate != null) {
			_hashCode = 29 * _hashCode + currentDebtDate.hashCode();
		}
		
		_hashCode = 29 * _hashCode + menteeId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DebtChangePk
	 */
	public DebtChangePk createPk()
	{
		return new DebtChangePk(debtChangeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.DebtChange: " );
		ret.append( "debtChangeId=" + debtChangeId );
		ret.append( ", currentTotalDebt=" + currentTotalDebt );
		ret.append( ", currentDebtType=" + currentDebtType );
		ret.append( ", currentDebtDescription=" + currentDebtDescription );
		ret.append( ", currentDebtDate=" + currentDebtDate );
		ret.append( ", menteeId=" + menteeId );
		return ret.toString();
	}

}
