/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Forms implements Serializable
{
	/** 
	 * This attribute maps to the column form_id in the forms table.
	 */
	protected int formId;

	/** 
	 * This attribute maps to the column mentor_id in the forms table.
	 */
	protected int mentorId;

	/** 
	 * This attribute maps to the column mentee_id in the forms table.
	 */
	protected int menteeId;

	/** 
	 * This attribute maps to the column meeting_time in the forms table.
	 */
	protected Date meetingTime;

	/** 
	 * This attribute maps to the column meeting_place in the forms table.
	 */
	protected String meetingPlace;

	/** 
	 * This attribute maps to the column meeting_notes in the forms table.
	 */
	protected String meetingNotes;

	/** 
	 * This attribute maps to the column next_meeting_goals in the forms table.
	 */
	protected String nextMeetingGoals;

	/** 
	 * This attribute maps to the column topic_covered in the forms table.
	 */
	protected String topicCovered;

	/** 
	 * This attribute maps to the column topic_covered_other in the forms table.
	 */
	protected String topicCoveredOther;

	/**
	 * Method 'Forms'
	 * 
	 */
	public Forms()
	{
	}

	/**
	 * Method 'getFormId'
	 * 
	 * @return int
	 */
	public int getFormId()
	{
		return formId;
	}

	/**
	 * Method 'setFormId'
	 * 
	 * @param formId
	 */
	public void setFormId(int formId)
	{
		this.formId = formId;
	}

	/**
	 * Method 'getMentorId'
	 * 
	 * @return int
	 */
	public int getMentorId()
	{
		return mentorId;
	}

	/**
	 * Method 'setMentorId'
	 * 
	 * @param mentorId
	 */
	public void setMentorId(int mentorId)
	{
		this.mentorId = mentorId;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'getMeetingTime'
	 * 
	 * @return Date
	 */
	public Date getMeetingTime()
	{
		return meetingTime;
	}

	/**
	 * Method 'setMeetingTime'
	 * 
	 * @param meetingTime
	 */
	public void setMeetingTime(Date meetingTime)
	{
		this.meetingTime = meetingTime;
	}

	/**
	 * Method 'getMeetingPlace'
	 * 
	 * @return String
	 */
	public String getMeetingPlace()
	{
		return meetingPlace;
	}

	/**
	 * Method 'setMeetingPlace'
	 * 
	 * @param meetingPlace
	 */
	public void setMeetingPlace(String meetingPlace)
	{
		this.meetingPlace = meetingPlace;
	}

	/**
	 * Method 'getMeetingNotes'
	 * 
	 * @return String
	 */
	public String getMeetingNotes()
	{
		return meetingNotes;
	}

	/**
	 * Method 'setMeetingNotes'
	 * 
	 * @param meetingNotes
	 */
	public void setMeetingNotes(String meetingNotes)
	{
		this.meetingNotes = meetingNotes;
	}

	/**
	 * Method 'getNextMeetingGoals'
	 * 
	 * @return String
	 */
	public String getNextMeetingGoals()
	{
		return nextMeetingGoals;
	}

	/**
	 * Method 'setNextMeetingGoals'
	 * 
	 * @param nextMeetingGoals
	 */
	public void setNextMeetingGoals(String nextMeetingGoals)
	{
		this.nextMeetingGoals = nextMeetingGoals;
	}

	/**
	 * Method 'getTopicCovered'
	 * 
	 * @return String
	 */
	public String getTopicCovered()
	{
		return topicCovered;
	}

	/**
	 * Method 'setTopicCovered'
	 * 
	 * @param topicCovered
	 */
	public void setTopicCovered(String topicCovered)
	{
		this.topicCovered = topicCovered;
	}

	/**
	 * Method 'getTopicCoveredOther'
	 * 
	 * @return String
	 */
	public String getTopicCoveredOther()
	{
		return topicCoveredOther;
	}

	/**
	 * Method 'setTopicCoveredOther'
	 * 
	 * @param topicCoveredOther
	 */
	public void setTopicCoveredOther(String topicCoveredOther)
	{
		this.topicCoveredOther = topicCoveredOther;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Forms)) {
			return false;
		}
		
		final Forms _cast = (Forms) _other;
		if (formId != _cast.formId) {
			return false;
		}
		
		if (mentorId != _cast.mentorId) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (meetingTime == null ? _cast.meetingTime != meetingTime : !meetingTime.equals( _cast.meetingTime )) {
			return false;
		}
		
		if (meetingPlace == null ? _cast.meetingPlace != meetingPlace : !meetingPlace.equals( _cast.meetingPlace )) {
			return false;
		}
		
		if (meetingNotes == null ? _cast.meetingNotes != meetingNotes : !meetingNotes.equals( _cast.meetingNotes )) {
			return false;
		}
		
		if (nextMeetingGoals == null ? _cast.nextMeetingGoals != nextMeetingGoals : !nextMeetingGoals.equals( _cast.nextMeetingGoals )) {
			return false;
		}
		
		if (topicCovered == null ? _cast.topicCovered != topicCovered : !topicCovered.equals( _cast.topicCovered )) {
			return false;
		}
		
		if (topicCoveredOther == null ? _cast.topicCoveredOther != topicCoveredOther : !topicCoveredOther.equals( _cast.topicCoveredOther )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + formId;
		_hashCode = 29 * _hashCode + mentorId;
		_hashCode = 29 * _hashCode + menteeId;
		if (meetingTime != null) {
			_hashCode = 29 * _hashCode + meetingTime.hashCode();
		}
		
		if (meetingPlace != null) {
			_hashCode = 29 * _hashCode + meetingPlace.hashCode();
		}
		
		if (meetingNotes != null) {
			_hashCode = 29 * _hashCode + meetingNotes.hashCode();
		}
		
		if (nextMeetingGoals != null) {
			_hashCode = 29 * _hashCode + nextMeetingGoals.hashCode();
		}
		
		if (topicCovered != null) {
			_hashCode = 29 * _hashCode + topicCovered.hashCode();
		}
		
		if (topicCoveredOther != null) {
			_hashCode = 29 * _hashCode + topicCoveredOther.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FormsPk
	 */
	public FormsPk createPk()
	{
		return new FormsPk(formId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.Forms: " );
		ret.append( "formId=" + formId );
		ret.append( ", mentorId=" + mentorId );
		ret.append( ", menteeId=" + menteeId );
		ret.append( ", meetingTime=" + meetingTime );
		ret.append( ", meetingPlace=" + meetingPlace );
		ret.append( ", meetingNotes=" + meetingNotes );
		ret.append( ", nextMeetingGoals=" + nextMeetingGoals );
		ret.append( ", topicCovered=" + topicCovered );
		ret.append( ", topicCoveredOther=" + topicCoveredOther );
		return ret.toString();
	}

}
