/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class HouseholdInfo implements Serializable
{
	/** 
	 * This attribute maps to the column household_info_id in the household_info table.
	 */
	protected int householdInfoId;

	/** 
	 * This attribute maps to the column household_info_name in the household_info table.
	 */
	protected String householdInfoName;

	/** 
	 * This attribute maps to the column household_info_date_of_birth in the household_info table.
	 */
	protected Date householdInfoDateOfBirth;

	/** 
	 * This attribute maps to the column household_info_adult in the household_info table.
	 */
	protected String householdInfoAdult;

	/** 
	 * This attribute maps to the column household_info_relationship in the household_info table.
	 */
	protected String householdInfoRelationship;

	/** 
	 * This attribute maps to the column household_info_notes in the household_info table.
	 */
	protected String householdInfoNotes;

	/** 
	 * This attribute maps to the column mentee_id in the household_info table.
	 */
	protected int menteeId;

	/**
	 * Method 'HouseholdInfo'
	 * 
	 */
	public HouseholdInfo()
	{
	}

	/**
	 * Method 'getHouseholdInfoId'
	 * 
	 * @return int
	 */
	public int getHouseholdInfoId()
	{
		return householdInfoId;
	}

	/**
	 * Method 'setHouseholdInfoId'
	 * 
	 * @param householdInfoId
	 */
	public void setHouseholdInfoId(int householdInfoId)
	{
		this.householdInfoId = householdInfoId;
	}

	/**
	 * Method 'getHouseholdInfoName'
	 * 
	 * @return String
	 */
	public String getHouseholdInfoName()
	{
		return householdInfoName;
	}

	/**
	 * Method 'setHouseholdInfoName'
	 * 
	 * @param householdInfoName
	 */
	public void setHouseholdInfoName(String householdInfoName)
	{
		this.householdInfoName = householdInfoName;
	}

	/**
	 * Method 'getHouseholdInfoDateOfBirth'
	 * 
	 * @return Date
	 */
	public Date getHouseholdInfoDateOfBirth()
	{
		return householdInfoDateOfBirth;
	}

	/**
	 * Method 'setHouseholdInfoDateOfBirth'
	 * 
	 * @param householdInfoDateOfBirth
	 */
	public void setHouseholdInfoDateOfBirth(Date householdInfoDateOfBirth)
	{
		this.householdInfoDateOfBirth = householdInfoDateOfBirth;
	}

	/**
	 * Method 'getHouseholdInfoAdult'
	 * 
	 * @return String
	 */
	public String getHouseholdInfoAdult()
	{
		return householdInfoAdult;
	}

	/**
	 * Method 'setHouseholdInfoAdult'
	 * 
	 * @param householdInfoAdult
	 */
	public void setHouseholdInfoAdult(String householdInfoAdult)
	{
		this.householdInfoAdult = householdInfoAdult;
	}

	/**
	 * Method 'getHouseholdInfoRelationship'
	 * 
	 * @return String
	 */
	public String getHouseholdInfoRelationship()
	{
		return householdInfoRelationship;
	}

	/**
	 * Method 'setHouseholdInfoRelationship'
	 * 
	 * @param householdInfoRelationship
	 */
	public void setHouseholdInfoRelationship(String householdInfoRelationship)
	{
		this.householdInfoRelationship = householdInfoRelationship;
	}

	/**
	 * Method 'getHouseholdInfoNotes'
	 * 
	 * @return String
	 */
	public String getHouseholdInfoNotes()
	{
		return householdInfoNotes;
	}

	/**
	 * Method 'setHouseholdInfoNotes'
	 * 
	 * @param householdInfoNotes
	 */
	public void setHouseholdInfoNotes(String householdInfoNotes)
	{
		this.householdInfoNotes = householdInfoNotes;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof HouseholdInfo)) {
			return false;
		}
		
		final HouseholdInfo _cast = (HouseholdInfo) _other;
		if (householdInfoId != _cast.householdInfoId) {
			return false;
		}
		
		if (householdInfoName == null ? _cast.householdInfoName != householdInfoName : !householdInfoName.equals( _cast.householdInfoName )) {
			return false;
		}
		
		if (householdInfoDateOfBirth == null ? _cast.householdInfoDateOfBirth != householdInfoDateOfBirth : !householdInfoDateOfBirth.equals( _cast.householdInfoDateOfBirth )) {
			return false;
		}
		
		if (householdInfoAdult == null ? _cast.householdInfoAdult != householdInfoAdult : !householdInfoAdult.equals( _cast.householdInfoAdult )) {
			return false;
		}
		
		if (householdInfoRelationship == null ? _cast.householdInfoRelationship != householdInfoRelationship : !householdInfoRelationship.equals( _cast.householdInfoRelationship )) {
			return false;
		}
		
		if (householdInfoNotes == null ? _cast.householdInfoNotes != householdInfoNotes : !householdInfoNotes.equals( _cast.householdInfoNotes )) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + householdInfoId;
		if (householdInfoName != null) {
			_hashCode = 29 * _hashCode + householdInfoName.hashCode();
		}
		
		if (householdInfoDateOfBirth != null) {
			_hashCode = 29 * _hashCode + householdInfoDateOfBirth.hashCode();
		}
		
		if (householdInfoAdult != null) {
			_hashCode = 29 * _hashCode + householdInfoAdult.hashCode();
		}
		
		if (householdInfoRelationship != null) {
			_hashCode = 29 * _hashCode + householdInfoRelationship.hashCode();
		}
		
		if (householdInfoNotes != null) {
			_hashCode = 29 * _hashCode + householdInfoNotes.hashCode();
		}
		
		_hashCode = 29 * _hashCode + menteeId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return HouseholdInfoPk
	 */
	public HouseholdInfoPk createPk()
	{
		return new HouseholdInfoPk(householdInfoId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.HouseholdInfo: " );
		ret.append( "householdInfoId=" + householdInfoId );
		ret.append( ", householdInfoName=" + householdInfoName );
		ret.append( ", householdInfoDateOfBirth=" + householdInfoDateOfBirth );
		ret.append( ", householdInfoAdult=" + householdInfoAdult );
		ret.append( ", householdInfoRelationship=" + householdInfoRelationship );
		ret.append( ", householdInfoNotes=" + householdInfoNotes );
		ret.append( ", menteeId=" + menteeId );
		return ret.toString();
	}

}
