/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class InitialDebt implements Serializable
{
	/** 
	 * This attribute maps to the column initial_debt_id in the initial_debt table.
	 */
	protected int initialDebtId;

	/** 
	 * This attribute maps to the column initial_debt_total in the initial_debt table.
	 */
	protected int initialDebtTotal;

	/** 
	 * This attribute represents whether the primitive attribute initialDebtTotal is null.
	 */
	protected boolean initialDebtTotalNull = true;

	/** 
	 * This attribute maps to the column initial_debt_type in the initial_debt table.
	 */
	protected String initialDebtType;

	/** 
	 * This attribute maps to the column initial_debt_amount in the initial_debt table.
	 */
	protected int initialDebtAmount;

	/** 
	 * This attribute represents whether the primitive attribute initialDebtAmount is null.
	 */
	protected boolean initialDebtAmountNull = true;

	/** 
	 * This attribute maps to the column initial_debt_description in the initial_debt table.
	 */
	protected String initialDebtDescription;

	/** 
	 * This attribute maps to the column mentee_id in the initial_debt table.
	 */
	protected int menteeId;

	/**
	 * Method 'InitialDebt'
	 * 
	 */
	public InitialDebt()
	{
	}

	/**
	 * Method 'getInitialDebtId'
	 * 
	 * @return int
	 */
	public int getInitialDebtId()
	{
		return initialDebtId;
	}

	/**
	 * Method 'setInitialDebtId'
	 * 
	 * @param initialDebtId
	 */
	public void setInitialDebtId(int initialDebtId)
	{
		this.initialDebtId = initialDebtId;
	}

	/**
	 * Method 'getInitialDebtTotal'
	 * 
	 * @return int
	 */
	public int getInitialDebtTotal()
	{
		return initialDebtTotal;
	}

	/**
	 * Method 'setInitialDebtTotal'
	 * 
	 * @param initialDebtTotal
	 */
	public void setInitialDebtTotal(int initialDebtTotal)
	{
		this.initialDebtTotal = initialDebtTotal;
		this.initialDebtTotalNull = false;
	}

	/**
	 * Method 'setInitialDebtTotalNull'
	 * 
	 * @param value
	 */
	public void setInitialDebtTotalNull(boolean value)
	{
		this.initialDebtTotalNull = value;
	}

	/**
	 * Method 'isInitialDebtTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isInitialDebtTotalNull()
	{
		return initialDebtTotalNull;
	}

	/**
	 * Method 'getInitialDebtType'
	 * 
	 * @return String
	 */
	public String getInitialDebtType()
	{
		return initialDebtType;
	}

	/**
	 * Method 'setInitialDebtType'
	 * 
	 * @param initialDebtType
	 */
	public void setInitialDebtType(String initialDebtType)
	{
		this.initialDebtType = initialDebtType;
	}

	/**
	 * Method 'getInitialDebtAmount'
	 * 
	 * @return int
	 */
	public int getInitialDebtAmount()
	{
		return initialDebtAmount;
	}

	/**
	 * Method 'setInitialDebtAmount'
	 * 
	 * @param initialDebtAmount
	 */
	public void setInitialDebtAmount(int initialDebtAmount)
	{
		this.initialDebtAmount = initialDebtAmount;
		this.initialDebtAmountNull = false;
	}

	/**
	 * Method 'setInitialDebtAmountNull'
	 * 
	 * @param value
	 */
	public void setInitialDebtAmountNull(boolean value)
	{
		this.initialDebtAmountNull = value;
	}

	/**
	 * Method 'isInitialDebtAmountNull'
	 * 
	 * @return boolean
	 */
	public boolean isInitialDebtAmountNull()
	{
		return initialDebtAmountNull;
	}

	/**
	 * Method 'getInitialDebtDescription'
	 * 
	 * @return String
	 */
	public String getInitialDebtDescription()
	{
		return initialDebtDescription;
	}

	/**
	 * Method 'setInitialDebtDescription'
	 * 
	 * @param initialDebtDescription
	 */
	public void setInitialDebtDescription(String initialDebtDescription)
	{
		this.initialDebtDescription = initialDebtDescription;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InitialDebt)) {
			return false;
		}
		
		final InitialDebt _cast = (InitialDebt) _other;
		if (initialDebtId != _cast.initialDebtId) {
			return false;
		}
		
		if (initialDebtTotal != _cast.initialDebtTotal) {
			return false;
		}
		
		if (initialDebtTotalNull != _cast.initialDebtTotalNull) {
			return false;
		}
		
		if (initialDebtType == null ? _cast.initialDebtType != initialDebtType : !initialDebtType.equals( _cast.initialDebtType )) {
			return false;
		}
		
		if (initialDebtAmount != _cast.initialDebtAmount) {
			return false;
		}
		
		if (initialDebtAmountNull != _cast.initialDebtAmountNull) {
			return false;
		}
		
		if (initialDebtDescription == null ? _cast.initialDebtDescription != initialDebtDescription : !initialDebtDescription.equals( _cast.initialDebtDescription )) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + initialDebtId;
		_hashCode = 29 * _hashCode + initialDebtTotal;
		_hashCode = 29 * _hashCode + (initialDebtTotalNull ? 1 : 0);
		if (initialDebtType != null) {
			_hashCode = 29 * _hashCode + initialDebtType.hashCode();
		}
		
		_hashCode = 29 * _hashCode + initialDebtAmount;
		_hashCode = 29 * _hashCode + (initialDebtAmountNull ? 1 : 0);
		if (initialDebtDescription != null) {
			_hashCode = 29 * _hashCode + initialDebtDescription.hashCode();
		}
		
		_hashCode = 29 * _hashCode + menteeId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InitialDebtPk
	 */
	public InitialDebtPk createPk()
	{
		return new InitialDebtPk(initialDebtId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.InitialDebt: " );
		ret.append( "initialDebtId=" + initialDebtId );
		ret.append( ", initialDebtTotal=" + initialDebtTotal );
		ret.append( ", initialDebtType=" + initialDebtType );
		ret.append( ", initialDebtAmount=" + initialDebtAmount );
		ret.append( ", initialDebtDescription=" + initialDebtDescription );
		ret.append( ", menteeId=" + menteeId );
		return ret.toString();
	}

}
