/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the initial_debt table.
 */
public class InitialDebtPk implements Serializable
{
	protected int initialDebtId;

	/** 
	 * This attribute represents whether the primitive attribute initialDebtId is null.
	 */
	protected boolean initialDebtIdNull;

	/** 
	 * Sets the value of initialDebtId
	 */
	public void setInitialDebtId(int initialDebtId)
	{
		this.initialDebtId = initialDebtId;
	}

	/** 
	 * Gets the value of initialDebtId
	 */
	public int getInitialDebtId()
	{
		return initialDebtId;
	}

	/**
	 * Method 'InitialDebtPk'
	 * 
	 */
	public InitialDebtPk()
	{
	}

	/**
	 * Method 'InitialDebtPk'
	 * 
	 * @param initialDebtId
	 */
	public InitialDebtPk(final int initialDebtId)
	{
		this.initialDebtId = initialDebtId;
	}

	/** 
	 * Sets the value of initialDebtIdNull
	 */
	public void setInitialDebtIdNull(boolean initialDebtIdNull)
	{
		this.initialDebtIdNull = initialDebtIdNull;
	}

	/** 
	 * Gets the value of initialDebtIdNull
	 */
	public boolean isInitialDebtIdNull()
	{
		return initialDebtIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InitialDebtPk)) {
			return false;
		}
		
		final InitialDebtPk _cast = (InitialDebtPk) _other;
		if (initialDebtId != _cast.initialDebtId) {
			return false;
		}
		
		if (initialDebtIdNull != _cast.initialDebtIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + initialDebtId;
		_hashCode = 29 * _hashCode + (initialDebtIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.InitialDebtPk: " );
		ret.append( "initialDebtId=" + initialDebtId );
		return ret.toString();
	}

}
