/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the mentor_mentee table.
 */
public class MentorMenteePk implements Serializable
{
	protected int mentorId;

	protected int menteeId;

	/** 
	 * This attribute represents whether the primitive attribute mentorId is null.
	 */
	protected boolean mentorIdNull;

	/** 
	 * This attribute represents whether the primitive attribute menteeId is null.
	 */
	protected boolean menteeIdNull;

	/** 
	 * Sets the value of mentorId
	 */
	public void setMentorId(int mentorId)
	{
		this.mentorId = mentorId;
	}

	/** 
	 * Gets the value of mentorId
	 */
	public int getMentorId()
	{
		return mentorId;
	}

	/** 
	 * Sets the value of menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/** 
	 * Gets the value of menteeId
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'MentorMenteePk'
	 * 
	 */
	public MentorMenteePk()
	{
	}

	/**
	 * Method 'MentorMenteePk'
	 * 
	 * @param mentorId
	 * @param menteeId
	 */
	public MentorMenteePk(final int mentorId, final int menteeId)
	{
		this.mentorId = mentorId;
		this.menteeId = menteeId;
	}

	/** 
	 * Sets the value of mentorIdNull
	 */
	public void setMentorIdNull(boolean mentorIdNull)
	{
		this.mentorIdNull = mentorIdNull;
	}

	/** 
	 * Gets the value of mentorIdNull
	 */
	public boolean isMentorIdNull()
	{
		return mentorIdNull;
	}

	/** 
	 * Sets the value of menteeIdNull
	 */
	public void setMenteeIdNull(boolean menteeIdNull)
	{
		this.menteeIdNull = menteeIdNull;
	}

	/** 
	 * Gets the value of menteeIdNull
	 */
	public boolean isMenteeIdNull()
	{
		return menteeIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MentorMenteePk)) {
			return false;
		}
		
		final MentorMenteePk _cast = (MentorMenteePk) _other;
		if (mentorId != _cast.mentorId) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (mentorIdNull != _cast.mentorIdNull) {
			return false;
		}
		
		if (menteeIdNull != _cast.menteeIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + mentorId;
		_hashCode = 29 * _hashCode + menteeId;
		_hashCode = 29 * _hashCode + (mentorIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (menteeIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.MentorMenteePk: " );
		ret.append( "mentorId=" + mentorId );
		ret.append( ", menteeId=" + menteeId );
		return ret.toString();
	}

}
