/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Mentees implements Serializable
{
	/** 
	 * This attribute maps to the column mentee_id in the mentees table.
	 */
	protected int menteeId;

	/** 
	 * This attribute maps to the column first_name in the mentees table.
	 */
	protected String firstName;

	/** 
	 * This attribute maps to the column last_name in the mentees table.
	 */
	protected String lastName;

	/** 
	 * This attribute maps to the column sex in the mentees table.
	 */
	protected String sex;

	/** 
	 * This attribute maps to the column age in the mentees table.
	 */
	protected int age;

	/** 
	 * This attribute represents whether the primitive attribute age is null.
	 */
	protected boolean ageNull = true;

	/** 
	 * This attribute maps to the column address in the mentees table.
	 */
	protected String address;

	/** 
	 * This attribute maps to the column zipcode in the mentees table.
	 */
	protected String zipcode;

	/** 
	 * This attribute maps to the column highest_education_level in the mentees table.
	 */
	protected String highestEducationLevel;

	/** 
	 * This attribute maps to the column pretraining_completed in the mentees table.
	 */
	protected String pretrainingCompleted;

	/** 
	 * This attribute maps to the column pretraining_date_complete in the mentees table.
	 */
	protected Date pretrainingDateComplete;

	/** 
	 * This attribute maps to the column ltp1_completed in the mentees table.
	 */
	protected String ltp1Completed;

	/** 
	 * This attribute maps to the column ltp1_date_complete in the mentees table.
	 */
	protected Date ltp1DateComplete;

	/** 
	 * This attribute maps to the column ltp2_completed in the mentees table.
	 */
	protected String ltp2Completed;

	/** 
	 * This attribute maps to the column ltp2_date_complete in the mentees table.
	 */
	protected Date ltp2DateComplete;

	/** 
	 * This attribute maps to the column ltp3_completed in the mentees table.
	 */
	protected String ltp3Completed;

	/** 
	 * This attribute maps to the column ltp3_date_complete in the mentees table.
	 */
	protected Date ltp3DateComplete;

	/** 
	 * This attribute maps to the column ltp4_completed in the mentees table.
	 */
	protected String ltp4Completed;

	/** 
	 * This attribute maps to the column ltp4_date_complete in the mentees table.
	 */
	protected Date ltp4DateComplete;

	/** 
	 * This attribute maps to the column other_goals in the mentees table.
	 */
	protected String otherGoals;

	/** 
	 * This attribute maps to the column current_saving in the mentees table.
	 */
	protected int currentSaving;

	/** 
	 * This attribute represents whether the primitive attribute currentSaving is null.
	 */
	protected boolean currentSavingNull = true;

	/** 
	 * This attribute maps to the column notes in the mentees table.
	 */
	protected String notes;

	/** 
	 * This attribute maps to the column middle_initial in the mentees table.
	 */
	protected String middleInitial;

	/** 
	 * This attribute maps to the column apt# in the mentees table.
	 */
	protected String apt;

	/** 
	 * This attribute maps to the column city in the mentees table.
	 */
	protected String city;

	/** 
	 * This attribute maps to the column state in the mentees table.
	 */
	protected String state;

	/** 
	 * This attribute maps to the column marital_status in the mentees table.
	 */
	protected String maritalStatus;

	/** 
	 * This attribute maps to the column birth_date in the mentees table.
	 */
	protected Date birthDate;

	/** 
	 * This attribute maps to the column emergency_contact in the mentees table.
	 */
	protected String emergencyContact;

	/** 
	 * This attribute maps to the column emergency_contact_description in the mentees table.
	 */
	protected String emergencyContactDescription;

	/** 
	 * This attribute maps to the column emergency_contact_info in the mentees table.
	 */
	protected String emergencyContactInfo;

	/**
	 * Method 'Mentees'
	 * 
	 */
	public Mentees()
	{
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'getFirstName'
	 * 
	 * @return String
	 */
	public String getFirstName()
	{
		return firstName;
	}

	/**
	 * Method 'setFirstName'
	 * 
	 * @param firstName
	 */
	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	/**
	 * Method 'getLastName'
	 * 
	 * @return String
	 */
	public String getLastName()
	{
		return lastName;
	}

	/**
	 * Method 'setLastName'
	 * 
	 * @param lastName
	 */
	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	/**
	 * Method 'getSex'
	 * 
	 * @return String
	 */
	public String getSex()
	{
		return sex;
	}

	/**
	 * Method 'setSex'
	 * 
	 * @param sex
	 */
	public void setSex(String sex)
	{
		this.sex = sex;
	}

	/**
	 * Method 'getAge'
	 * 
	 * @return int
	 */
	public int getAge()
	{
		return age;
	}

	/**
	 * Method 'setAge'
	 * 
	 * @param age
	 */
	public void setAge(int age)
	{
		this.age = age;
		this.ageNull = false;
	}

	/**
	 * Method 'setAgeNull'
	 * 
	 * @param value
	 */
	public void setAgeNull(boolean value)
	{
		this.ageNull = value;
	}

	/**
	 * Method 'isAgeNull'
	 * 
	 * @return boolean
	 */
	public boolean isAgeNull()
	{
		return ageNull;
	}

	/**
	 * Method 'getAddress'
	 * 
	 * @return String
	 */
	public String getAddress()
	{
		return address;
	}

	/**
	 * Method 'setAddress'
	 * 
	 * @param address
	 */
	public void setAddress(String address)
	{
		this.address = address;
	}

	/**
	 * Method 'getZipcode'
	 * 
	 * @return String
	 */
	public String getZipcode()
	{
		return zipcode;
	}

	/**
	 * Method 'setZipcode'
	 * 
	 * @param zipcode
	 */
	public void setZipcode(String zipcode)
	{
		this.zipcode = zipcode;
	}

	/**
	 * Method 'getHighestEducationLevel'
	 * 
	 * @return String
	 */
	public String getHighestEducationLevel()
	{
		return highestEducationLevel;
	}

	/**
	 * Method 'setHighestEducationLevel'
	 * 
	 * @param highestEducationLevel
	 */
	public void setHighestEducationLevel(String highestEducationLevel)
	{
		this.highestEducationLevel = highestEducationLevel;
	}

	/**
	 * Method 'getPretrainingCompleted'
	 * 
	 * @return String
	 */
	public String getPretrainingCompleted()
	{
		return pretrainingCompleted;
	}

	/**
	 * Method 'setPretrainingCompleted'
	 * 
	 * @param pretrainingCompleted
	 */
	public void setPretrainingCompleted(String pretrainingCompleted)
	{
		this.pretrainingCompleted = pretrainingCompleted;
	}

	/**
	 * Method 'getPretrainingDateComplete'
	 * 
	 * @return Date
	 */
	public Date getPretrainingDateComplete()
	{
		return pretrainingDateComplete;
	}

	/**
	 * Method 'setPretrainingDateComplete'
	 * 
	 * @param pretrainingDateComplete
	 */
	public void setPretrainingDateComplete(Date pretrainingDateComplete)
	{
		this.pretrainingDateComplete = pretrainingDateComplete;
	}

	/**
	 * Method 'getLtp1Completed'
	 * 
	 * @return String
	 */
	public String getLtp1Completed()
	{
		return ltp1Completed;
	}

	/**
	 * Method 'setLtp1Completed'
	 * 
	 * @param ltp1Completed
	 */
	public void setLtp1Completed(String ltp1Completed)
	{
		this.ltp1Completed = ltp1Completed;
	}

	/**
	 * Method 'getLtp1DateComplete'
	 * 
	 * @return Date
	 */
	public Date getLtp1DateComplete()
	{
		return ltp1DateComplete;
	}

	/**
	 * Method 'setLtp1DateComplete'
	 * 
	 * @param ltp1DateComplete
	 */
	public void setLtp1DateComplete(Date ltp1DateComplete)
	{
		this.ltp1DateComplete = ltp1DateComplete;
	}

	/**
	 * Method 'getLtp2Completed'
	 * 
	 * @return String
	 */
	public String getLtp2Completed()
	{
		return ltp2Completed;
	}

	/**
	 * Method 'setLtp2Completed'
	 * 
	 * @param ltp2Completed
	 */
	public void setLtp2Completed(String ltp2Completed)
	{
		this.ltp2Completed = ltp2Completed;
	}

	/**
	 * Method 'getLtp2DateComplete'
	 * 
	 * @return Date
	 */
	public Date getLtp2DateComplete()
	{
		return ltp2DateComplete;
	}

	/**
	 * Method 'setLtp2DateComplete'
	 * 
	 * @param ltp2DateComplete
	 */
	public void setLtp2DateComplete(Date ltp2DateComplete)
	{
		this.ltp2DateComplete = ltp2DateComplete;
	}

	/**
	 * Method 'getLtp3Completed'
	 * 
	 * @return String
	 */
	public String getLtp3Completed()
	{
		return ltp3Completed;
	}

	/**
	 * Method 'setLtp3Completed'
	 * 
	 * @param ltp3Completed
	 */
	public void setLtp3Completed(String ltp3Completed)
	{
		this.ltp3Completed = ltp3Completed;
	}

	/**
	 * Method 'getLtp3DateComplete'
	 * 
	 * @return Date
	 */
	public Date getLtp3DateComplete()
	{
		return ltp3DateComplete;
	}

	/**
	 * Method 'setLtp3DateComplete'
	 * 
	 * @param ltp3DateComplete
	 */
	public void setLtp3DateComplete(Date ltp3DateComplete)
	{
		this.ltp3DateComplete = ltp3DateComplete;
	}

	/**
	 * Method 'getLtp4Completed'
	 * 
	 * @return String
	 */
	public String getLtp4Completed()
	{
		return ltp4Completed;
	}

	/**
	 * Method 'setLtp4Completed'
	 * 
	 * @param ltp4Completed
	 */
	public void setLtp4Completed(String ltp4Completed)
	{
		this.ltp4Completed = ltp4Completed;
	}

	/**
	 * Method 'getLtp4DateComplete'
	 * 
	 * @return Date
	 */
	public Date getLtp4DateComplete()
	{
		return ltp4DateComplete;
	}

	/**
	 * Method 'setLtp4DateComplete'
	 * 
	 * @param ltp4DateComplete
	 */
	public void setLtp4DateComplete(Date ltp4DateComplete)
	{
		this.ltp4DateComplete = ltp4DateComplete;
	}

	/**
	 * Method 'getOtherGoals'
	 * 
	 * @return String
	 */
	public String getOtherGoals()
	{
		return otherGoals;
	}

	/**
	 * Method 'setOtherGoals'
	 * 
	 * @param otherGoals
	 */
	public void setOtherGoals(String otherGoals)
	{
		this.otherGoals = otherGoals;
	}

	/**
	 * Method 'getCurrentSaving'
	 * 
	 * @return int
	 */
	public int getCurrentSaving()
	{
		return currentSaving;
	}

	/**
	 * Method 'setCurrentSaving'
	 * 
	 * @param currentSaving
	 */
	public void setCurrentSaving(int currentSaving)
	{
		this.currentSaving = currentSaving;
		this.currentSavingNull = false;
	}

	/**
	 * Method 'setCurrentSavingNull'
	 * 
	 * @param value
	 */
	public void setCurrentSavingNull(boolean value)
	{
		this.currentSavingNull = value;
	}

	/**
	 * Method 'isCurrentSavingNull'
	 * 
	 * @return boolean
	 */
	public boolean isCurrentSavingNull()
	{
		return currentSavingNull;
	}

	/**
	 * Method 'getNotes'
	 * 
	 * @return String
	 */
	public String getNotes()
	{
		return notes;
	}

	/**
	 * Method 'setNotes'
	 * 
	 * @param notes
	 */
	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	/**
	 * Method 'getMiddleInitial'
	 * 
	 * @return String
	 */
	public String getMiddleInitial()
	{
		return middleInitial;
	}

	/**
	 * Method 'setMiddleInitial'
	 * 
	 * @param middleInitial
	 */
	public void setMiddleInitial(String middleInitial)
	{
		this.middleInitial = middleInitial;
	}

	/**
	 * Method 'getApt'
	 * 
	 * @return String
	 */
	public String getApt()
	{
		return apt;
	}

	/**
	 * Method 'setApt'
	 * 
	 * @param apt
	 */
	public void setApt(String apt)
	{
		this.apt = apt;
	}

	/**
	 * Method 'getCity'
	 * 
	 * @return String
	 */
	public String getCity()
	{
		return city;
	}

	/**
	 * Method 'setCity'
	 * 
	 * @param city
	 */
	public void setCity(String city)
	{
		this.city = city;
	}

	/**
	 * Method 'getState'
	 * 
	 * @return String
	 */
	public String getState()
	{
		return state;
	}

	/**
	 * Method 'setState'
	 * 
	 * @param state
	 */
	public void setState(String state)
	{
		this.state = state;
	}

	/**
	 * Method 'getMaritalStatus'
	 * 
	 * @return String
	 */
	public String getMaritalStatus()
	{
		return maritalStatus;
	}

	/**
	 * Method 'setMaritalStatus'
	 * 
	 * @param maritalStatus
	 */
	public void setMaritalStatus(String maritalStatus)
	{
		this.maritalStatus = maritalStatus;
	}

	/**
	 * Method 'getBirthDate'
	 * 
	 * @return Date
	 */
	public Date getBirthDate()
	{
		return birthDate;
	}

	/**
	 * Method 'setBirthDate'
	 * 
	 * @param birthDate
	 */
	public void setBirthDate(Date birthDate)
	{
		this.birthDate = birthDate;
	}

	/**
	 * Method 'getEmergencyContact'
	 * 
	 * @return String
	 */
	public String getEmergencyContact()
	{
		return emergencyContact;
	}

	/**
	 * Method 'setEmergencyContact'
	 * 
	 * @param emergencyContact
	 */
	public void setEmergencyContact(String emergencyContact)
	{
		this.emergencyContact = emergencyContact;
	}

	/**
	 * Method 'getEmergencyContactDescription'
	 * 
	 * @return String
	 */
	public String getEmergencyContactDescription()
	{
		return emergencyContactDescription;
	}

	/**
	 * Method 'setEmergencyContactDescription'
	 * 
	 * @param emergencyContactDescription
	 */
	public void setEmergencyContactDescription(String emergencyContactDescription)
	{
		this.emergencyContactDescription = emergencyContactDescription;
	}

	/**
	 * Method 'getEmergencyContactInfo'
	 * 
	 * @return String
	 */
	public String getEmergencyContactInfo()
	{
		return emergencyContactInfo;
	}

	/**
	 * Method 'setEmergencyContactInfo'
	 * 
	 * @param emergencyContactInfo
	 */
	public void setEmergencyContactInfo(String emergencyContactInfo)
	{
		this.emergencyContactInfo = emergencyContactInfo;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Mentees)) {
			return false;
		}
		
		final Mentees _cast = (Mentees) _other;
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		if (firstName == null ? _cast.firstName != firstName : !firstName.equals( _cast.firstName )) {
			return false;
		}
		
		if (lastName == null ? _cast.lastName != lastName : !lastName.equals( _cast.lastName )) {
			return false;
		}
		
		if (sex == null ? _cast.sex != sex : !sex.equals( _cast.sex )) {
			return false;
		}
		
		if (age != _cast.age) {
			return false;
		}
		
		if (ageNull != _cast.ageNull) {
			return false;
		}
		
		if (address == null ? _cast.address != address : !address.equals( _cast.address )) {
			return false;
		}
		
		if (zipcode == null ? _cast.zipcode != zipcode : !zipcode.equals( _cast.zipcode )) {
			return false;
		}
		
		if (highestEducationLevel == null ? _cast.highestEducationLevel != highestEducationLevel : !highestEducationLevel.equals( _cast.highestEducationLevel )) {
			return false;
		}
		
		if (pretrainingCompleted == null ? _cast.pretrainingCompleted != pretrainingCompleted : !pretrainingCompleted.equals( _cast.pretrainingCompleted )) {
			return false;
		}
		
		if (pretrainingDateComplete == null ? _cast.pretrainingDateComplete != pretrainingDateComplete : !pretrainingDateComplete.equals( _cast.pretrainingDateComplete )) {
			return false;
		}
		
		if (ltp1Completed == null ? _cast.ltp1Completed != ltp1Completed : !ltp1Completed.equals( _cast.ltp1Completed )) {
			return false;
		}
		
		if (ltp1DateComplete == null ? _cast.ltp1DateComplete != ltp1DateComplete : !ltp1DateComplete.equals( _cast.ltp1DateComplete )) {
			return false;
		}
		
		if (ltp2Completed == null ? _cast.ltp2Completed != ltp2Completed : !ltp2Completed.equals( _cast.ltp2Completed )) {
			return false;
		}
		
		if (ltp2DateComplete == null ? _cast.ltp2DateComplete != ltp2DateComplete : !ltp2DateComplete.equals( _cast.ltp2DateComplete )) {
			return false;
		}
		
		if (ltp3Completed == null ? _cast.ltp3Completed != ltp3Completed : !ltp3Completed.equals( _cast.ltp3Completed )) {
			return false;
		}
		
		if (ltp3DateComplete == null ? _cast.ltp3DateComplete != ltp3DateComplete : !ltp3DateComplete.equals( _cast.ltp3DateComplete )) {
			return false;
		}
		
		if (ltp4Completed == null ? _cast.ltp4Completed != ltp4Completed : !ltp4Completed.equals( _cast.ltp4Completed )) {
			return false;
		}
		
		if (ltp4DateComplete == null ? _cast.ltp4DateComplete != ltp4DateComplete : !ltp4DateComplete.equals( _cast.ltp4DateComplete )) {
			return false;
		}
		
		if (otherGoals == null ? _cast.otherGoals != otherGoals : !otherGoals.equals( _cast.otherGoals )) {
			return false;
		}
		
		if (currentSaving != _cast.currentSaving) {
			return false;
		}
		
		if (currentSavingNull != _cast.currentSavingNull) {
			return false;
		}
		
		if (notes == null ? _cast.notes != notes : !notes.equals( _cast.notes )) {
			return false;
		}
		
		if (middleInitial == null ? _cast.middleInitial != middleInitial : !middleInitial.equals( _cast.middleInitial )) {
			return false;
		}
		
		if (apt == null ? _cast.apt != apt : !apt.equals( _cast.apt )) {
			return false;
		}
		
		if (city == null ? _cast.city != city : !city.equals( _cast.city )) {
			return false;
		}
		
		if (state == null ? _cast.state != state : !state.equals( _cast.state )) {
			return false;
		}
		
		if (maritalStatus == null ? _cast.maritalStatus != maritalStatus : !maritalStatus.equals( _cast.maritalStatus )) {
			return false;
		}
		
		if (birthDate == null ? _cast.birthDate != birthDate : !birthDate.equals( _cast.birthDate )) {
			return false;
		}
		
		if (emergencyContact == null ? _cast.emergencyContact != emergencyContact : !emergencyContact.equals( _cast.emergencyContact )) {
			return false;
		}
		
		if (emergencyContactDescription == null ? _cast.emergencyContactDescription != emergencyContactDescription : !emergencyContactDescription.equals( _cast.emergencyContactDescription )) {
			return false;
		}
		
		if (emergencyContactInfo == null ? _cast.emergencyContactInfo != emergencyContactInfo : !emergencyContactInfo.equals( _cast.emergencyContactInfo )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + menteeId;
		if (firstName != null) {
			_hashCode = 29 * _hashCode + firstName.hashCode();
		}
		
		if (lastName != null) {
			_hashCode = 29 * _hashCode + lastName.hashCode();
		}
		
		if (sex != null) {
			_hashCode = 29 * _hashCode + sex.hashCode();
		}
		
		_hashCode = 29 * _hashCode + age;
		_hashCode = 29 * _hashCode + (ageNull ? 1 : 0);
		if (address != null) {
			_hashCode = 29 * _hashCode + address.hashCode();
		}
		
		if (zipcode != null) {
			_hashCode = 29 * _hashCode + zipcode.hashCode();
		}
		
		if (highestEducationLevel != null) {
			_hashCode = 29 * _hashCode + highestEducationLevel.hashCode();
		}
		
		if (pretrainingCompleted != null) {
			_hashCode = 29 * _hashCode + pretrainingCompleted.hashCode();
		}
		
		if (pretrainingDateComplete != null) {
			_hashCode = 29 * _hashCode + pretrainingDateComplete.hashCode();
		}
		
		if (ltp1Completed != null) {
			_hashCode = 29 * _hashCode + ltp1Completed.hashCode();
		}
		
		if (ltp1DateComplete != null) {
			_hashCode = 29 * _hashCode + ltp1DateComplete.hashCode();
		}
		
		if (ltp2Completed != null) {
			_hashCode = 29 * _hashCode + ltp2Completed.hashCode();
		}
		
		if (ltp2DateComplete != null) {
			_hashCode = 29 * _hashCode + ltp2DateComplete.hashCode();
		}
		
		if (ltp3Completed != null) {
			_hashCode = 29 * _hashCode + ltp3Completed.hashCode();
		}
		
		if (ltp3DateComplete != null) {
			_hashCode = 29 * _hashCode + ltp3DateComplete.hashCode();
		}
		
		if (ltp4Completed != null) {
			_hashCode = 29 * _hashCode + ltp4Completed.hashCode();
		}
		
		if (ltp4DateComplete != null) {
			_hashCode = 29 * _hashCode + ltp4DateComplete.hashCode();
		}
		
		if (otherGoals != null) {
			_hashCode = 29 * _hashCode + otherGoals.hashCode();
		}
		
		_hashCode = 29 * _hashCode + currentSaving;
		_hashCode = 29 * _hashCode + (currentSavingNull ? 1 : 0);
		if (notes != null) {
			_hashCode = 29 * _hashCode + notes.hashCode();
		}
		
		if (middleInitial != null) {
			_hashCode = 29 * _hashCode + middleInitial.hashCode();
		}
		
		if (apt != null) {
			_hashCode = 29 * _hashCode + apt.hashCode();
		}
		
		if (city != null) {
			_hashCode = 29 * _hashCode + city.hashCode();
		}
		
		if (state != null) {
			_hashCode = 29 * _hashCode + state.hashCode();
		}
		
		if (maritalStatus != null) {
			_hashCode = 29 * _hashCode + maritalStatus.hashCode();
		}
		
		if (birthDate != null) {
			_hashCode = 29 * _hashCode + birthDate.hashCode();
		}
		
		if (emergencyContact != null) {
			_hashCode = 29 * _hashCode + emergencyContact.hashCode();
		}
		
		if (emergencyContactDescription != null) {
			_hashCode = 29 * _hashCode + emergencyContactDescription.hashCode();
		}
		
		if (emergencyContactInfo != null) {
			_hashCode = 29 * _hashCode + emergencyContactInfo.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MenteesPk
	 */
	public MenteesPk createPk()
	{
		return new MenteesPk(menteeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.Mentees: " );
		ret.append( "menteeId=" + menteeId );
		ret.append( ", firstName=" + firstName );
		ret.append( ", lastName=" + lastName );
		ret.append( ", sex=" + sex );
		ret.append( ", age=" + age );
		ret.append( ", address=" + address );
		ret.append( ", zipcode=" + zipcode );
		ret.append( ", highestEducationLevel=" + highestEducationLevel );
		ret.append( ", pretrainingCompleted=" + pretrainingCompleted );
		ret.append( ", pretrainingDateComplete=" + pretrainingDateComplete );
		ret.append( ", ltp1Completed=" + ltp1Completed );
		ret.append( ", ltp1DateComplete=" + ltp1DateComplete );
		ret.append( ", ltp2Completed=" + ltp2Completed );
		ret.append( ", ltp2DateComplete=" + ltp2DateComplete );
		ret.append( ", ltp3Completed=" + ltp3Completed );
		ret.append( ", ltp3DateComplete=" + ltp3DateComplete );
		ret.append( ", ltp4Completed=" + ltp4Completed );
		ret.append( ", ltp4DateComplete=" + ltp4DateComplete );
		ret.append( ", otherGoals=" + otherGoals );
		ret.append( ", currentSaving=" + currentSaving );
		ret.append( ", notes=" + notes );
		ret.append( ", middleInitial=" + middleInitial );
		ret.append( ", apt=" + apt );
		ret.append( ", city=" + city );
		ret.append( ", state=" + state );
		ret.append( ", maritalStatus=" + maritalStatus );
		ret.append( ", birthDate=" + birthDate );
		ret.append( ", emergencyContact=" + emergencyContact );
		ret.append( ", emergencyContactDescription=" + emergencyContactDescription );
		ret.append( ", emergencyContactInfo=" + emergencyContactInfo );
		return ret.toString();
	}

}
