/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import careownership.dao.*;
import careownership.factory.*;
import careownership.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class MentorMentee implements Serializable
{
	/** 
	 * This attribute maps to the column mentor_id in the mentor_mentee table.
	 */
	protected int mentorId;

	/** 
	 * This attribute maps to the column mentee_id in the mentor_mentee table.
	 */
	protected int menteeId;

	/**
	 * Method 'MentorMentee'
	 * 
	 */
	public MentorMentee()
	{
	}

	/**
	 * Method 'getMentorId'
	 * 
	 * @return int
	 */
	public int getMentorId()
	{
		return mentorId;
	}

	/**
	 * Method 'setMentorId'
	 * 
	 * @param mentorId
	 */
	public void setMentorId(int mentorId)
	{
		this.mentorId = mentorId;
	}

	/**
	 * Method 'getMenteeId'
	 * 
	 * @return int
	 */
	public int getMenteeId()
	{
		return menteeId;
	}

	/**
	 * Method 'setMenteeId'
	 * 
	 * @param menteeId
	 */
	public void setMenteeId(int menteeId)
	{
		this.menteeId = menteeId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MentorMentee)) {
			return false;
		}
		
		final MentorMentee _cast = (MentorMentee) _other;
		if (mentorId != _cast.mentorId) {
			return false;
		}
		
		if (menteeId != _cast.menteeId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + mentorId;
		_hashCode = 29 * _hashCode + menteeId;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return MentorMenteePk
	 */
	public MentorMenteePk createPk()
	{
		return new MentorMenteePk(mentorId, menteeId);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.MentorMentee: " );
		ret.append( "mentorId=" + mentorId );
		ret.append( ", menteeId=" + menteeId );
		return ret.toString();
	}

}
