/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the mentors table.
 */
public class MentorsPk implements Serializable
{
	protected int mentorId;

	/** 
	 * This attribute represents whether the primitive attribute mentorId is null.
	 */
	protected boolean mentorIdNull;

	/** 
	 * Sets the value of mentorId
	 */
	public void setMentorId(int mentorId)
	{
		this.mentorId = mentorId;
	}

	/** 
	 * Gets the value of mentorId
	 */
	public int getMentorId()
	{
		return mentorId;
	}

	/**
	 * Method 'MentorsPk'
	 * 
	 */
	public MentorsPk()
	{
	}

	/**
	 * Method 'MentorsPk'
	 * 
	 * @param mentorId
	 */
	public MentorsPk(final int mentorId)
	{
		this.mentorId = mentorId;
	}

	/** 
	 * Sets the value of mentorIdNull
	 */
	public void setMentorIdNull(boolean mentorIdNull)
	{
		this.mentorIdNull = mentorIdNull;
	}

	/** 
	 * Gets the value of mentorIdNull
	 */
	public boolean isMentorIdNull()
	{
		return mentorIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof MentorsPk)) {
			return false;
		}
		
		final MentorsPk _cast = (MentorsPk) _other;
		if (mentorId != _cast.mentorId) {
			return false;
		}
		
		if (mentorIdNull != _cast.mentorIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + mentorId;
		_hashCode = 29 * _hashCode + (mentorIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.MentorsPk: " );
		ret.append( "mentorId=" + mentorId );
		return ret.toString();
	}

}
