/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the staff table.
 */
public class StaffPk implements Serializable
{
	protected int staffId;

	/** 
	 * This attribute represents whether the primitive attribute staffId is null.
	 */
	protected boolean staffIdNull;

	/** 
	 * Sets the value of staffId
	 */
	public void setStaffId(int staffId)
	{
		this.staffId = staffId;
	}

	/** 
	 * Gets the value of staffId
	 */
	public int getStaffId()
	{
		return staffId;
	}

	/**
	 * Method 'StaffPk'
	 * 
	 */
	public StaffPk()
	{
	}

	/**
	 * Method 'StaffPk'
	 * 
	 * @param staffId
	 */
	public StaffPk(final int staffId)
	{
		this.staffId = staffId;
	}

	/** 
	 * Sets the value of staffIdNull
	 */
	public void setStaffIdNull(boolean staffIdNull)
	{
		this.staffIdNull = staffIdNull;
	}

	/** 
	 * Gets the value of staffIdNull
	 */
	public boolean isStaffIdNull()
	{
		return staffIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof StaffPk)) {
			return false;
		}
		
		final StaffPk _cast = (StaffPk) _other;
		if (staffId != _cast.staffId) {
			return false;
		}
		
		if (staffIdNull != _cast.staffIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + staffId;
		_hashCode = 29 * _hashCode + (staffIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "careownership.dto.StaffPk: " );
		ret.append( "staffId=" + staffId );
		return ret.toString();
	}

}
