/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package careownership.jdbc;

import careownership.dao.*;
import careownership.factory.*;
import java.util.Date;
import careownership.dto.*;
import careownership.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class HouseholdInfoDaoImpl extends AbstractDAO implements HouseholdInfoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT household_info_id, household_info_name, household_info_date_of_birth, household_info_adult, household_info_relationship, household_info_notes, mentee_id FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( household_info_id, household_info_name, household_info_date_of_birth, household_info_adult, household_info_relationship, household_info_notes, mentee_id ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET household_info_id = ?, household_info_name = ?, household_info_date_of_birth = ?, household_info_adult = ?, household_info_relationship = ?, household_info_notes = ?, mentee_id = ? WHERE household_info_id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE household_info_id = ?";

	/** 
	 * Index of column household_info_id
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_ID = 1;

	/** 
	 * Index of column household_info_name
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_NAME = 2;

	/** 
	 * Index of column household_info_date_of_birth
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_DATE_OF_BIRTH = 3;

	/** 
	 * Index of column household_info_adult
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_ADULT = 4;

	/** 
	 * Index of column household_info_relationship
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_RELATIONSHIP = 5;

	/** 
	 * Index of column household_info_notes
	 */
	protected static final int COLUMN_HOUSEHOLD_INFO_NOTES = 6;

	/** 
	 * Index of column mentee_id
	 */
	protected static final int COLUMN_MENTEE_ID = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column household_info_id
	 */
	protected static final int PK_COLUMN_HOUSEHOLD_INFO_ID = 1;

	/** 
	 * Inserts a new row in the household_info table.
	 */
	public HouseholdInfoPk insert(HouseholdInfo dto) throws HouseholdInfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getHouseholdInfoId() );
			stmt.setString( index++, dto.getHouseholdInfoName() );
			stmt.setDate(index++, dto.getHouseholdInfoDateOfBirth()==null ? null : new java.sql.Date( dto.getHouseholdInfoDateOfBirth().getTime() ) );
			stmt.setString( index++, dto.getHouseholdInfoAdult() );
			stmt.setString( index++, dto.getHouseholdInfoRelationship() );
			stmt.setString( index++, dto.getHouseholdInfoNotes() );
			stmt.setInt( index++, dto.getMenteeId() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setHouseholdInfoId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HouseholdInfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the household_info table.
	 */
	public void update(HouseholdInfoPk pk, HouseholdInfo dto) throws HouseholdInfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getHouseholdInfoId() );
			stmt.setString( index++, dto.getHouseholdInfoName() );
			stmt.setDate(index++, dto.getHouseholdInfoDateOfBirth()==null ? null : new java.sql.Date( dto.getHouseholdInfoDateOfBirth().getTime() ) );
			stmt.setString( index++, dto.getHouseholdInfoAdult() );
			stmt.setString( index++, dto.getHouseholdInfoRelationship() );
			stmt.setString( index++, dto.getHouseholdInfoNotes() );
			stmt.setInt( index++, dto.getMenteeId() );
			stmt.setInt( 8, pk.getHouseholdInfoId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HouseholdInfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the household_info table.
	 */
	public void delete(HouseholdInfoPk pk) throws HouseholdInfoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getHouseholdInfoId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HouseholdInfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the household_info table that matches the specified primary-key value.
	 */
	public HouseholdInfo findByPrimaryKey(HouseholdInfoPk pk) throws HouseholdInfoDaoException
	{
		return findByPrimaryKey( pk.getHouseholdInfoId() );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_id = :householdInfoId'.
	 */
	public HouseholdInfo findByPrimaryKey(int householdInfoId) throws HouseholdInfoDaoException
	{
		HouseholdInfo ret[] = findByDynamicSelect( SQL_SELECT + " WHERE household_info_id = ?", new Object[] {  new Integer(householdInfoId) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria ''.
	 */
	public HouseholdInfo[] findAll() throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY household_info_id", null );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'mentee_id = :menteeId'.
	 */
	public HouseholdInfo[] findByMentees(int menteeId) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentee_id = ?", new Object[] {  new Integer(menteeId) } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_id = :householdInfoId'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoIdEquals(int householdInfoId) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_id = ? ORDER BY household_info_id", new Object[] {  new Integer(householdInfoId) } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_name = :householdInfoName'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoNameEquals(String householdInfoName) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_name = ? ORDER BY household_info_name", new Object[] { householdInfoName } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_date_of_birth = :householdInfoDateOfBirth'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoDateOfBirthEquals(Date householdInfoDateOfBirth) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_date_of_birth = ? ORDER BY household_info_date_of_birth", new Object[] { householdInfoDateOfBirth==null ? null : new java.sql.Date( householdInfoDateOfBirth.getTime() ) } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_adult = :householdInfoAdult'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoAdultEquals(String householdInfoAdult) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_adult = ? ORDER BY household_info_adult", new Object[] { householdInfoAdult } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_relationship = :householdInfoRelationship'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoRelationshipEquals(String householdInfoRelationship) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_relationship = ? ORDER BY household_info_relationship", new Object[] { householdInfoRelationship } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'household_info_notes = :householdInfoNotes'.
	 */
	public HouseholdInfo[] findWhereHouseholdInfoNotesEquals(String householdInfoNotes) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE household_info_notes = ? ORDER BY household_info_notes", new Object[] { householdInfoNotes } );
	}

	/** 
	 * Returns all rows from the household_info table that match the criteria 'mentee_id = :menteeId'.
	 */
	public HouseholdInfo[] findWhereMenteeIdEquals(int menteeId) throws HouseholdInfoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mentee_id = ? ORDER BY mentee_id", new Object[] {  new Integer(menteeId) } );
	}

	/**
	 * Method 'HouseholdInfoDaoImpl'
	 * 
	 */
	public HouseholdInfoDaoImpl()
	{
	}

	/**
	 * Method 'HouseholdInfoDaoImpl'
	 * 
	 * @param userConn
	 */
	public HouseholdInfoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "household_info";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected HouseholdInfo fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			HouseholdInfo dto = new HouseholdInfo();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected HouseholdInfo[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			HouseholdInfo dto = new HouseholdInfo();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		HouseholdInfo ret[] = new HouseholdInfo[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(HouseholdInfo dto, ResultSet rs) throws SQLException
	{
		dto.setHouseholdInfoId( rs.getInt( COLUMN_HOUSEHOLD_INFO_ID ) );
		dto.setHouseholdInfoName( rs.getString( COLUMN_HOUSEHOLD_INFO_NAME ) );
		dto.setHouseholdInfoDateOfBirth( rs.getDate(COLUMN_HOUSEHOLD_INFO_DATE_OF_BIRTH ) );
		dto.setHouseholdInfoAdult( rs.getString( COLUMN_HOUSEHOLD_INFO_ADULT ) );
		dto.setHouseholdInfoRelationship( rs.getString( COLUMN_HOUSEHOLD_INFO_RELATIONSHIP ) );
		dto.setHouseholdInfoNotes( rs.getString( COLUMN_HOUSEHOLD_INFO_NOTES ) );
		dto.setMenteeId( rs.getInt( COLUMN_MENTEE_ID ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(HouseholdInfo dto)
	{
	}

	/** 
	 * Returns all rows from the household_info table that match the specified arbitrary SQL statement
	 */
	public HouseholdInfo[] findByDynamicSelect(String sql, Object[] sqlParams) throws HouseholdInfoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HouseholdInfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the household_info table that match the specified arbitrary SQL statement
	 */
	public HouseholdInfo[] findByDynamicWhere(String sql, Object[] sqlParams) throws HouseholdInfoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new HouseholdInfoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
